### ISSUE TITLE
How is cc3  cocos creator 3D embedded in Vue or react

### ISSUE THREAD

**Issue by yjwSurCode** [cocos/cocos-engine#10461]
cocos creator2.x can be embedded in Vue or react projects

**Comment by yjwSurCode** [comment]
no iframe

**Comment by minggo** [comment]
Any problem to integrate with them?

**Comment by yjwSurCode** [comment]
![Uploading image.png…]()


Do you have this problem？

**Comment by yjwSurCode** [comment]
CC. Generated by cocos package How to introduce JS

> Any problem to integrate with them?

**Comment by yjwSurCode** [comment]
> Any problem to integrate with them?

cc.js:1 Uncaught (in promise) TypeError: Wn.btDefaultCollisionConfiguration is not a constructor
    at new e (cc.js:1:823907)
    at new e (cc.js:1:741365)
    at cc.js:1:744628
    at cc.js:1:744707
    at t.emit (ammo-instantiated-07963f79.js:1:125986)
    at t.n._initOnRendererInitialized (ammo-instantiated-07963f79.js:1:1100076)
    at t.emit (ammo-instantiated-07963f79.js:1:125968)
    at t.n._safeEmit (ammo-instantiated-07963f79.js:1:963385)
    at t.n._setRenderPipeline (ammo-instantiated-07963f79.js:1:963320)
    at ammo-instantiated-07963f79.js:1:962912

**Comment by minggo** [comment]
@shrinktofit any idea?

**Comment by shrinktofit** [comment]
> 

Could you upload your demo code?
