### ISSUE TITLE
[3.4.0] custom native-engine error: spawnSync /bin/sh ENOENT

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#10520]
I've tried to custom engine for v3.4.0. Our project require too many bug fixes that already resolved on these branchs.
My steps are following the tutorial on [Engine customization Workfolow](https://docs.cocos.com/creator/3.0/manual/en/advanced-topics/engine-customization.html)

Machine: iMac
Mac version: Big Sur 11.4

preproduce steps:
- pull the native-engine repo
- checkout branch v3.4.0
- cd to native-engine directory
- npm install
- gulp init

The process has been corrupted by the error: spawnSync /bin/sh ENOENT.

```
admin@Admins-iMac engine-native % npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

changed 2 packages, and audited 523 packages in 12s

18 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (1 moderate, 25 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
admin@Admins-iMac engine-native % gulp init
[11:33:40] Using gulpfile ~/Documents/workspace/cocos34engine/engine-native/gulpfile.js
[11:33:40] Starting 'init'...
Cloning into 'external'...
remote: Enumerating objects: 18105, done.
remote: Counting objects: 100% (18105/18105), done.
remote: Compressing objects: 100% (13137/13137), done.
remote: Total 18105 (delta 4927), reused 17717 (delta 4827), pack-reused 0
Receiving objects: 100% (18105/18105), 606.25 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (4927/4927), done.
Note: switching to 'acbdb6702b8362abaea0ca524325066e646a1d69'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (19309/19309), done.
acbdb670 (grafted, HEAD, tag: v3d-gfx-80) Disable cxx exceptions for spirv-tools (#196)
[11:41:54] 'init' errored after 8.23 min
[11:41:54] Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:1074:20)
    at spawnSync (child_process.js:629:24)
    at execSync (child_process.js:674:15)
    at execSync (/Users/admin/Documents/workspace/cocos34engine/engine-native/gulpfile.js:62:5)
    at /Users/admin/Documents/workspace/cocos34engine/engine-native/gulpfile.js:133:5
    at init (/Users/admin/Documents/workspace/cocos34engine/engine-native/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:416:15)
    at runBound (domain.js:427:12)
    at asyncRunner (/Users/admin/Documents/workspace/cocos34engine/engine-native/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by minggo** [comment]
@qingwabote yep, there are duplicated. We should remove one.

**Comment by minggo** [comment]
I removed duplicated codes in https://github.com/cocos/cocos-engine/pull/10917.
