### ISSUE TITLE
[3.4.2] custom native-engine Error: spawnSync C:\Windows\System32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by speakissilver** [cocos/cocos-engine#10688]
### Cocos Creator version

3.4.2

### System information

window10

### Issue description

i try use https://github.com/cocos/cocos-engine/issues/10520 method
my python version is 2.7.5 pyinstaller is 4.10

==> Ready to download 'v3-console-16.zip' from 'https://github.com/cocos2d/console-binary/archive/v3-console-16.zip'
Traceback (most recent call last):
  File "download-bin.py", line 301, in <module>
    main()
  File "download-bin.py", line 296, in main
    installer.run("", opts.remove_downloaded, opts.force_update, opts.download_only)
  File "download-bin.py", line 241, in run
    self.download_zip_file()
  File "download-bin.py", line 203, in download_zip_file
    self.download_file()
  File "download-bin.py", line 91, in download_file
    u = urllib2.urlopen(self._url)
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1148, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:499: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
[17:56:40] 'init' errored after 3.18 s
[17:56:40] Error: Command failed: python download-bin.py --remove-download no
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at execSync (C:\Users\ray.c\Desktop\engine-native\gulpfile.js:62:5)
    at C:\Users\ray.c\Desktop\engine-native\gulpfile.js:133:5
    at init (C:\Users\ray.c\Desktop\engine-native\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (C:\Users\ray.c\Desktop\engine-native\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

### Relevant error log output

[17:49:26] Error: spawnSync C:\Windows\System32\cmd.exe ENOENT
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at execSync (child_process.js:647:15)
    at execSync (C:\Users\ray.c\Desktop\engine-native\gulpfile.js:62:5)
    at C:\Users\ray.c\Desktop\engine-native\gulpfile.js:133:5
    at init (C:\Users\ray.c\Desktop\engine-native\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (C:\Users\ray.c\Desktop\engine-native\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

### Steps to reproduce

cmd
cd  engine-native
gulp init

**Comment by timlyeee** [comment]
Well, still, gulp init is useless now, there's no submodule and no coco2d-console to be downloaded.

https://github.com/cocos/cocos-engine/issues/10520 did answer that you might only need to download the external and nothing more.

**Comment by speakissilver** [comment]
@jareguo 
ok
this issue has been resolved
But still hope that the file content can be corrected

https://docs.cocos.com/creator/manual/zh/advanced-topics/engine-customization.html

**Comment by minggo** [comment]
@speakissilver i corrected the documentation in https://github.com/cocos/cocos-docs/pull/2044.
