### ISSUE TITLE
Chrome throw ERR_INSUFFICIENT_RESOURCES error when open devtools

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#11046]
### Cocos Creator version

3.5.0

### System information

Chrome on Window

### Issue description

![image](https://user-images.githubusercontent.com/8321365/168034485-319e5298-c01f-4e21-9227-71f5423a844c.png)
![image](https://user-images.githubusercontent.com/8321365/168034515-99145fff-1e1c-402b-a50f-a2171c6321de.png)
![img_v2_4c51f7f2-cc34-4c58-b6aa-61dadb5caf6g](https://user-images.githubusercontent.com/8321365/203517990-29eba99c-56fc-4b9b-bfb9-7f11cf2386dc.jpg)

### Relevant error log output

[localhost-1669203844605.zip](https://github.com/cocos/cocos-engine/files/10080587/localhost-1669203844605.zip)
[project(1).zip](https://github.com/cocos/cocos-engine/files/10081766/project.1.zip)

### Steps to reproduce

a big project, only when devtools opened has this error.

**Comment by xianyinchen** [comment]
As the test file is not available, we will continue to follow up and the issue is closed first.

**Comment by PPpro** [comment]
feadback from ByteDance team

**Comment by PPpro** [comment]
there is some error in log, please try fixing them at first, like
```
2022-11-24T07:04:45.995Z - warn: [Scene] Can not use 'editor' attribute, 'UIBindingInfo' not inherits from Components.Error: [Scene] Can not use 'editor' attribute, 'UIBindingInfo' not inherits from Components.
    at warn (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:140155:12)
    at warnID (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:140369:5)
    at CCClass (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:117232:9)
    at eval (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:225194:21)
    at eval (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:226250:18)
    at Object.execute (file:///E:/Code_Client/branches/upgrade3.6.2/temp/programming/packer-driver/targets/editor/chunks/e5/e5a6296662fd9fc3bfbee299702bb86d7cdab206.js:84:11)
    at doExec (C:\CocosDashboard_1.0.14\resources\.editors\Creator\3.6.2\resources\app.asar\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)



2022-11-24T07:04:46.151Z - warn: [Scene] The type of "CriManaCocosPlayer.moviePath" must be CCString, not String.Error: [Scene] The type of "CriManaCocosPlayer.moviePath" must be CCString, not String.
    at warn (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:140155:12)
    at warnID (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:140369:5)
    at parseType (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:227343:11)
    at preprocessAttrs (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:227483:11)
    at declareProperties (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:117188:7)
    at CCClass (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:117225:5)
    at eval (E:\Code_Client\branches\upgrade3.6.2\engine-dev\bin\.cache\dev\editor\bundled\index.js:225194:21)
``` 


I'll close this issue fow now
