### ISSUE TITLE
[v3.6][bug] VideoPlayer script error

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#11310]
```
TypeError: camera.matViewProj.equals is not a function
        at VideoPlayerImplJSB.syncMatrix (jsb-adapter/jsb-engine.js:5392:54)
        at VideoPlayer.update (src/cocos-js/cc.js:140069:30)
        at eval (eval at createInvokeImplJit (src/cocos-js/cc.js:29878:40), <anonymous>:3:65)
        at ReusableInvoker._invoke (src/cocos-js/cc.js:29885:19)
        at ReusableInvoker.invoke (src/cocos-js/cc.js:29867:22)
        at ComponentScheduler.updatePhase (src/cocos-js/cc.js:30017:36)
        at Director.tick (src/cocos-js/cc.js:34547:41)
        at callback (src/cocos-js/cc.js:30849:30)
        at tick (jsb-adapter/jsb-builtin.js:607:7)
```

**Comment by dumganhar** [comment]
WebView test also triggers similar issue.
```
TypeError: camera.matViewProj.equals is not a function
        at WebViewImplJSB.syncMatrix (jsb-adapter/jsb-engine.js:5632:54)
        at WebView.update (src/cocos-js/cc.js:140591:30)
        at eval (eval at createInvokeImplJit (src/cocos-js/cc.js:29878:40), <anonymous>:3:65)
        at ReusableInvoker._invoke (src/cocos-js/cc.js:29885:19)
        at ReusableInvoker.invoke (src/cocos-js/cc.js:29867:22)
        at ComponentScheduler.updatePhase (src/cocos-js/cc.js:30017:36)
        at Director.tick (src/cocos-js/cc.js:34547:41)
        at callback (src/cocos-js/cc.js:30849:30)
        at tick (jsb-adapter/jsb-builtin.js:607:7)
```
