### ISSUE TITLE
Unable to export ParticleSystem2D to plist file

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#11474]
### Cocos Creator version

3.5.1

### System information

Windows 10 Editor

### Issue description

Trying to export any kind of ParticleSystem2D to a .plist file results in the following errors:

```
[Scene] 'Renderable2D.prototype.srcBlendFactor' has been removed. Error: [Scene] 'Renderable2D.prototype.srcBlendFactor' has been removed.  
    at error (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:145346:10) 
    at removePropertyLog (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:160167:5) 
    at ParticleSystem2D.get (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:160184:16) 
    at Particle2DManager._applyPlistData (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\particle-2d\index.ccc:1:1949) 
    at Particle2DManager.exportParticlePlist (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\particle-2d\index.ccc:1:1425) 
    at async PrefabSceneFacade.exportParticlePlist (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\facade\general-scene-facade.ccc:1:18854) 
```

```
[Scene] 'Renderable2D.prototype.dstBlendFactor' has been removed. Error: [Scene] 'Renderable2D.prototype.dstBlendFactor' has been removed.  
    at error (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:145346:10) 
    at removePropertyLog (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:160167:5) 
    at ParticleSystem2D.get (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:160184:16) 
    at Particle2DManager._applyPlistData (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\particle-2d\index.ccc:1:1989) 
    at Particle2DManager.exportParticlePlist (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\particle-2d\index.ccc:1:1425) 
    at async PrefabSceneFacade.exportParticlePlist (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\facade\general-scene-facade.ccc:1:18854) 
```

```
[Window] Cannot set property 'uuid' of nullTypeError: Cannot set property 'uuid' of null 
    at HTMLElement.<anonymous> (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.5.1\resources\resources\3d\engine\editor\inspector\components\particle-system-2d.js:122:51) 
```

![image](https://user-images.githubusercontent.com/82378750/173242079-5017dbaa-7e88-4706-9283-13f17aaa2668.png)

### Steps to reproduce

Create a new empty project. Add an empty node to the scene and then add a ParticleSystem2D component to this node. Set a sprite for the particle system and then try to export the particle system to plist file which results in error.

**Comment by gdoudeng** [comment]
+1

**Comment by OnlyKoei** [comment]
测试 3.6.0-072219 已修复
