### ISSUE TITLE
Error while deleting transition in Animation Graph

### ISSUE THREAD

**Issue by Biodam** [cocos/cocos-engine#12749]
### Cocos Creator version

3.5.1

### System information

Windows 11

### Issue description

Press delete with a animation graph transition selected

### Relevant error log output

  [Window] Assertion failed: <no-message>
Error: Assertion failed: <no-message>
at <process:scene>
at assertIsTrue (C:\Projects\BitCake\cocos-engine\bin\.cache\dev\editor\bundled\index.js:216917:11)
at StateMachine.disconnect (C:\Projects\BitCake\cocos-engine\bin\.cache\dev\editor\bundled\index.js:209982:33)
at SceneAnimationGraph.removeTransition (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\animation-graph\dist\scene-animation-graph.ccc:1:27655)
at Object.removeTransition (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\animation-graph\dist\scene.ccc:1:3853)
at PluginManager.executeSceneScript (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\plugin.ccc:1:2205)
at PrefabSceneFacade.executeSceneScriptMethod (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\facade\general-scene-facade.ccc:1:10018)
at SceneFacadeManager.executeSceneScriptMethod (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\facade\scene-facade-manager.ccc:1:17037)
at C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\3d\manager\ipc.ccc:1:1776
at EventEmitter.<anonymous> (C:\CocosDashboard_1.2.0\resources\.editors\Creator\3.5.1\resources\app.asar\builtin\scene\dist\script\public\ipc\webview.ccc:1:767)
at EventEmitter.emit (events.js:315:20)

### Steps to reproduce

1. Create a animation graph transition
2. Press delete with it selected

(Maybe a open/close of the animation graph is needed to reproduce the error)

**Comment by arsen2010** [comment]
I did not reproduce the error,  remove one selected transition is so normal operation in animation graph design, we dont allow it happen easily in a released version, sorry, without any change , i would close this issue.
