### ISSUE TITLE
Web platform emits errors on window resizing.

### ISSUE THREAD

**Issue by yiwenxue** [cocos/cocos-engine#12949]
### Cocos Creator version

Develop

### System information

Windows 11, editor preview

### Issue description
Web platform emits errors on window resizing.

cocos/core/platform/view.ts

```Typescript
    private _updateAdaptResult (event: jsb.WindowEvent) {}
```

event is always undefined.

![image](https://user-images.githubusercontent.com/24495793/192935517-bca7862b-6140-4bf8-afc1-c2e8a07c196d.png)

### Relevant error log output

``` 
// Before:
@property(...)
myProp;
// After:
@property(...)
myProp = 0;
2022-09-29T03:52:58.206Z - log: [Scene] 'cc.ParticleSystem2D.color' hides inherited property 'cc.UIRenderer.color'. To make the current property override that implementation, add the `override: true` attribute please.
2022-09-29T03:52:58.245Z - log: [Scene] No needs to indicate the 'cc.Boolean' attribute for "cc.Terrain._receiveShadow", which its default value is type of Boolean.
2022-09-29T03:52:58.245Z - log: [Scene] No needs to indicate the 'cc.Boolean' attribute for "cc.Terrain._useNormalmap", which its default value is type of Boolean.
2022-09-29T03:52:58.246Z - log: [Scene] No needs to indicate the 'cc.Boolean' attribute for "cc.Terrain._usePBR", which its default value is type of Boolean.
2022-09-29T03:52:58.246Z - log: [Scene] No needs to indicate the 'cc.Boolean' attribute for "cc.Terrain._lodEnable", which its default value is type of Boolean.
2022-09-29T03:52:58.338Z - info: [Scene] [Physics][Bullet]: Using asmjs Bullet libs.
2022-09-29T03:52:58.352Z - info: [Scene] [PHYSICS]: using builtin.
2022-09-29T03:52:58.518Z - log: [Scene] Cocos Creator v3.6.1
2022-09-29T03:52:58.518Z - info: [Scene] Forward render pipeline initialized.
2022-09-29T03:52:58.563Z - warn: [Scene] The vm module of Node.js is deprecated in the renderer process and will be removed.Error: [Scene] The vm module of Node.js is deprecated in the renderer process and will be removed.
    at Function.o._load (electron/js2c/renderer_init.js:33:285)
    at Function._load (D:\3.6\editor\app\node_modules\cc\preload.ts:127:35)
    at Module.require [as __require] (internal/modules/cjs/loader.js:959:19)
    at Module.require (D:\3.6\editor\app\node_modules\@editor\creator\dist\require.js:1:689)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\3.6\editor\app\node_modules\@editor\lib-programming\src\executor\pack-mod-instantiation.ts:2:1)
    at Object.<anonymous> (D:\3.6\editor\app\node_modules\@editor\lib-programming\dist\executor\pack-mod-instantiation.js:113:3)
2022-09-29T03:52:58.717Z - warn: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.Error: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.
    at warn (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208335:12)
    at warnID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208549:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233780:7)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/0e/0e0cbe977fd5f97f137d58d636b88b62be297e2b.js:35:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:52:58.953Z - error: [Scene] 'Renderable2D' is removed since v3.6.0, please use 'UIRenderer' instead.Error: [Scene] 'Renderable2D' is removed since v3.6.0, please use 'UIRenderer' instead.
    at error (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208353:12)
    at errorID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208553:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233775:9)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/61/6130f8238fac9ebabe590b125b07ecf357108812.js:28:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:52:58.964Z - warn: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.Error: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.
    at warn (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208335:12)
    at warnID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208549:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233780:7)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/37/37f174a8c3f77f6093b27d7a901cfdb8376e53b8.js:54:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:52:59.149Z - info: [Scene] [PHYSICS]: switch from builtin to physx.
2022-09-29T03:53:00.038Z - warn: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.Error: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.
    at warn (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208335:12)
    at warnID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208549:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233780:7)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/0e/0e0cbe977fd5f97f137d58d636b88b62be297e2b.js:35:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:53:00.080Z - error: [Scene] 'Renderable2D' is removed since v3.6.0, please use 'UIRenderer' instead.Error: [Scene] 'Renderable2D' is removed since v3.6.0, please use 'UIRenderer' instead.
    at error (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208353:12)
    at errorID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208553:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233775:9)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/61/6130f8238fac9ebabe590b125b07ecf357108812.js:28:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:53:00.082Z - warn: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.Error: [Scene] 'BaseNode' is deprecated since v3.7.0, please use 'Node' instead.
    at warn (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208335:12)
    at warnID (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:208549:5)
    at _checkObsoleteByName (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233780:7)
    at __checkObsolete__ (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:233800:7)
    at Object.execute (file:///D:/3.6/cocos-test-projects/temp/programming/packer-driver/targets/editor/chunks/37/37f174a8c3f77f6093b27d7a901cfdb8376e53b8.js:54:7)
    at doExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:517:30)
    at postOrderExec (D:\3.6\editor\app\node_modules\@editor\lib-programming\static\executor\systemjs-bridge\out\index.js:508:21)
2022-09-29T03:53:02.008Z - error: [Window] { status: 701, msg: 'Data Write Failure', path: 'log/add' }
2022-09-29T03:58:02.621Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.637Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.804Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.821Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.838Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.854Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
2022-09-29T03:58:02.871Z - error: [Scene] Cannot read property 'windowId' of undefinedTypeError: Cannot read property 'windowId' of undefined
    at View._updateAdaptResult (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:211066:47)
    at ScreenAdapter.emit (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:189759:28)
    at ScreenAdapter._updateContainer (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301634:18)
    at ScreenAdapter._resizeFrame (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301534:16)
    at eval (D:\3.6\editor\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:301432:18)
```

### Steps to reproduce

1. open a random scene
2. resize the preview window

OR
1. preview in the browser
2. change the resolution

### Minimal reproduction project

hello-world is enough

**Comment by yiwenxue** [comment]
Fixed
