### ISSUE TITLE
ParticleSystem2D is still broken while using CustomMaterial (v3.6.1)

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#12976]
### Cocos Creator version

3.6.1

### System information

Windows 10 Editor

### Issue description

This was not an issue in v3.5 but right now I can't use a customMaterial with a ParticleSystem2D. 
The first issue is that after exporting the particle system to .plist file I get countless amount of errors inside the editor:
```
[Scene] Buffer binding 'CCLocal' at set 2 binding 0 is not boundedError: [Scene] Buffer binding 'CCLocal' at set 2 binding 0 is not bounded 
    at error (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:134282:12) 
    at WebGL2CmdFuncBindStates (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:250602:11) 
    at WebGL2PrimaryCommandBuffer.bindStates (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:253012:11) 
    at WebGL2PrimaryCommandBuffer.draw (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:252899:20) 
    at Proxy.newFunc (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:113940:37) 
    at UIPhase.render (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:145428:23) 
    at ForwardStage.render (C:\CocosDashboard_1.1.2\resources\.editors\Creator\3.6.1\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:246819:25) 
```
The other issue is that even though I'm using a custom material using effect of "builtin-billboard" and the technique of "add-smooth" it doesn't properly save this setting. 

The first time that I select the "add-smooth" technique it is applied properly inside the editor preview like the below picture:
![image](https://user-images.githubusercontent.com/82378750/193630497-1f406278-c38f-4868-ad3b-2fb578681f64.png)

But after saving the custom material it immediately reverts back to the default "add" technique (although the "add-smooth" technique is selected in the properties).
![image](https://user-images.githubusercontent.com/82378750/193635988-70c8b298-aae5-4396-a587-3913e4c4a434.png)

### Steps to reproduce

Just create a new ParticleSystem2D node in an empty project and try to use a custom material for that particle system using different techniques.

### Minimal reproduction project

[Test2D.zip](https://github.com/cocos/cocos-engine/files/9699444/Test2D.zip)

**Comment by pandamicro** [comment]
Particle system doesn't support custom material yet, it would probably be planned with refactorization of ParticleSystem
