### ISSUE TITLE
[3.6.2] Downlaod with https throw error on Android platform

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13311]
### Cocos Creator version

3.6.2

### System information

Android 12

### Issue description

this is  the log, throw error with ssl handle.

``` logcat
2022-11-10 14:40:20.048 6613-6648/com.test.cocos D/Cocos: 14:40:20 [DEBUG]: In the constructor of HttpClient!
2022-11-10 14:40:20.158 6613-6648/com.test.cocos D/Cocos: 14:40:20 [DEBUG]: D/ JS: onClickTest, version.mainifest:{"packageUrl":"https://api.wzlgame.cn/upload/remote-assets/","remoteManifestUrl":"https://api.wzlgame.cn/upload/remote-assets/project.manifest","remoteVersionUrl":"https://api.wzlgame.cn/upload/remote-assets/version.manifest","version":"1.0.1"}
2022-11-10 14:40:22.852 6613-6730/com.test.cocos W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-11-10 14:40:22.853 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
2022-11-10 14:40:22.853 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2022-11-10 14:40:22.853 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2022-11-10 14:40:22.853 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2022-11-10 14:40:22.853 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
2022-11-10 14:40:22.854 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
2022-11-10 14:40:22.855 6613-6730/com.test.cocos W/System.err:     at com.cocos.lib.CocosHttpURLConnection.connect(CocosHttpURLConnection.java:152)
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
2022-11-10 14:40:22.856 6613-6730/com.test.cocos W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2022-11-10 14:40:22.857 6613-6730/com.test.cocos W/System.err: 	... 20 more
2022-11-10 14:40:22.858 6613-6730/com.test.cocos W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-11-10 14:40:22.858 6613-6730/com.test.cocos W/System.err: 	... 33 more
2022-11-10 14:40:22.858 6613-6730/com.test.cocos E/CocosHttpURLConnection: connectjavax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022-11-10 14:40:22.862 6613-6648/com.test.cocos D/Cocos: 14:40:22 [DEBUG]: D/ Response failed, error buffer: connect failed
2022-11-10 14:40:22.862 6613-6648/com.test.cocos D/Cocos: 14:40:22 [DEBUG]: D/ JS: [object Object]
```

### Steps to reproduce

test project.
[https-test.zip](https://github.com/cocos/cocos-engine/files/10019137/https-test.zip)

**Comment by novain1102** [comment]
https://api.wzlgame.cn 
![WXWorkCapture_16687607536649](https://user-images.githubusercontent.com/18634782/202660941-ecf9e688-36b8-4fbb-9b32-7b1f914f103e.png)
Since the security certificate used by this Https site has not been recognized by CA, it may be risky
