### ISSUE TITLE
1.4rc1 new coffeescript component error

### ISSUE THREAD

**Issue by javyliu** [cocos/cocos-engine#1470]
Error: ENOENT: no such file or directory, open 'E:\game_projects\test_21\library\imports\40\40d9b3e4-98ea-4d49-afbc-db44114d6f4a.js.map'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:186:20)
at Object.fs.readFileSync (fs.js:508:33)
at Object.fs.readFileSync (ELECTRON_ASAR.js:523:29)
at getBabelSourceMaps (E:\ccc1.4_rc1\resources\app.asar\editor\page\refine-sourcemap.js:1:942)
at Stream.refineSourceMap (E:\ccc1.4_rc1\resources\app.asar\editor\page\refine-sourcemap.js:1:2260)
at Stream.stream.write (E:\ccc1.4_rc1\resources\app.asar\node_modules\through\index.js:26:11)
at write (E:\ccc1.4_rc1\resources\app.asar\node_modules\vinyl-buffer\node_modules\readable-stream\lib\_stream_readable.js:623:24)
at flow (E:\ccc1.4_rc1\resources\app.asar\node_modules\vinyl-buffer\node_modules\readable-stream\lib\_stream_readable.js:632:7)
at E:\ccc1.4_rc1\resources\app.asar\editor\core\compiler.js:1:1022
at E:\ccc1.4_rc1\resources\app.asar\editor\core\compiler.js:1:466
at BrowserWindow.<anonymous> (E:\ccc1.4_rc1\resources\app.asar\editor\core\compiler.js:1:2045)
at BrowserWindow.g (events.js:286:16)
at emitOne (events.js:101:20)
at BrowserWindow.emit (events.js:188:7)

**Comment by nantas** [comment]
Fixed in next rc release.
