### ISSUE TITLE
3.8 Spine相关问题

### ISSUE THREAD

**Issue by bgxd9592** [cocos/cocos-engine#16018]
### Cocos Creator version

3.8.0

### System information

Windows 10   预览

### Issue description

1.使用动画融合时，getCurrent无法获取其他层级的动画
2.无法修改sp.spine.Slot的color属性

### Relevant error log output

1.getCurrent(1)为null
2.
```
2023-08-18 10:26:31 [PreviewInEditor] Cannot set property color of [object Object] which has only a getter
TypeError: Cannot set property color of [object Object] which has only a getter
at CEs.start (file:///D:/NewProject_1/temp/programming/packer-driver/targets/editor/chunks/98/989bd38e1db06452cc85ad1569e785269148b2d7.js:36:22)（此处为Bone.color = color;）
at eval (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:48450:16)
at OneOffInvoker.eval [as _invoke] (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:48263:9)
at OneOffInvoker.invoke (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:48379:16)
at ComponentScheduler.startPhase (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:48649:29)
at Director.tick (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:19999:35)
at Game._updateCallback (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:21108:22)
at updateCallback (D:\Cocos\Creator\3.8.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:92937:20)
```

### Steps to reproduce

```
import { _decorator, Component, Node, sp } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('CEs')
export class CEs extends Component {
    start() {
        this.getComponent(sp.Skeleton).setAnimation(0, "AnimName", false);
        this.getComponent(sp.Skeleton).setAnimation(1, "AnimName2", true);
        console.log(this.getComponent(sp.Skeleton).getCurrent(1))  //此处返回Null,getCurrent(0)会正常返回0的动画
        var Bone = this.getComponent(sp.Skeleton).findSlot("13");
        var color = new sp.spine.Color;
        console.log(Bone);
        color.set(1, 1, 1, 0);
        Bone.color = color;//此处报错，报错内容同Relevant error log output内第二栏
    }
}
```

**Comment by Canvasfull** [comment]
问题 1 你可以测试下 3.8.1 最新的社区版本 应该是已经修复了。
Windows下载地址：[https://download.cocos.org/CocosCreator/v3.8.1/CocosCreator-v3.8.1-win-082912.zip 5](https://download.cocos.org/CocosCreator/v3.8.1/CocosCreator-v3.8.1-win-082912.zip)
Mac下载地址：[https://download.cocos.org/CocosCreator/v3.8.1/CocosCreator-v3.8.1-mac-082912.zip 7](https://download.cocos.org/CocosCreator/v3.8.1/CocosCreator-v3.8.1-mac-082912.zip)

3.8.1 社区： https://forum.cocos.org/t/topic/152207

问题 2  这个是 对接 Wasm 版本后 使用上的差异。我们后续看看怎么优化这里的代码

在 C++ 版本里暴露出来的 接口只有 getColor 并没有 setColor 的用法。

<img width="476" alt="Screenshot 2023-08-31 at 15 53 35" src="https://github.com/cocos/cocos-engine/assets/2398658/febb7460-987e-4e5e-baad-4caa2336aae9">

暂时使用直接设置 color.a = 0。

<img width="498" alt="Screenshot 2023-08-31 at 15 51 44" src="https://github.com/cocos/cocos-engine/assets/2398658/3b9eb5a9-8a3b-45b4-b497-7fd9a751371a">

<img width="256" alt="Screenshot 2023-08-31 at 15 51 25" src="https://github.com/cocos/cocos-engine/assets/2398658/12cef021-a42d-4ff1-999c-dab804cd69ee">
