### ISSUE TITLE
RealCurve property hides all next properties

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16240]
### Cocos Creator version

3.8.0

### System information

Windows 11

### Issue description

Add one RealCurve property in the component then all next properties will be hidden.

```
    @property public test1 = 1;
    @property ({ type: RealCurve}) public curve1: RealCurve = new RealCurve();
    @property public test2 = 1;
```

![image](https://github.com/cocos/cocos-engine/assets/758680/35e581fe-5ffe-4d08-9c6e-fbd40e97c6c8)

### Relevant error log output

```
 [Window] Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
at changeDumpValueToCurveValue (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\builtin\scene\dist\contributions\ui-kit\ui-prop\types\real-curve.ccc:1:1112)
at Object.update (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\builtin\scene\dist\contributions\ui-kit\ui-prop\types\real-curve.ccc:1:901)
at Object.update (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\builtin\scene\dist\contributions\ui-kit\ui-prop\dump.ccc:1:4629)
at HTMLElement.initRender (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\node_modules\@editor\creator-ui-kit\dist\renderer.ccc:2:1525886)
at HTMLElement.render (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\node_modules\@editor\creator-ui-kit\dist\renderer.ccc:2:1525755)
at C:\ProgramData\cocos\editors\Creator\3.8.0\resources\resources\3d\engine\editor\inspector\utils\prop.js:277:15
at Array.forEach (<anonymous>)
at C:\ProgramData\cocos\editors\Creator\3.8.0\resources\resources\3d\engine\editor\inspector\utils\prop.js:205:29
at Object.<anonymous> (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\resources\3d\engine\editor\inspector\components\base.js:14:5)
at HTMLElement.update (C:\ProgramData\cocos\editors\Creator\3.8.0\resources\app.asar\node_modules\@editor\creator-ui-kit\dist\renderer.ccc:2:1529781)
```

### Steps to reproduce

```
    @property public test1 = 1;
    @property ({ type: RealCurve}) public curve1: RealCurve = new RealCurve();
    @property public test2 = 1;
```

**Comment by yufengctbu** [comment]
This issue has been fixed in version 3.8.4
