### ISSUE TITLE
[2.4.12] WebView field still exists in jsb-adapter 

### ISSUE THREAD

**Issue by sszyc8** [cocos/cocos-engine#16643]
### Cocos Creator version

2.4.12

### System information

MacOS,Android

### Issue description

Creator removes the webview function and Export Android project `WebView field still exists in jsb-adapter `

### Relevant error log output

Build Failed: Error: WebView field still exists in jsb-adapter
at DestroyableTransform. (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\editor\share\build-jsb-adapter.ccc:1:947)
at DestroyableTransform.emit (events.js:327:22)
at DestroyableTransform.emit (domain.js:529:15)
at addChunk (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\readable-stream\lib_stream_readable.js:291:12)
at readableAddChunk (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\readable-stream\lib_stream_readable.js:278:11)
at DestroyableTransform.push (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\readable-stream\lib_stream_readable.js:245:10)
at DestroyableTransform.push (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\readable-stream\lib_stream_transform.js:148:32)
at push (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\vinyl-buffer\index.js:25:12)
at BufferList._callback (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\vinyl-buffer\index.js:20:7)
at BufferList.end (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\bl\bl.js:105:10)
at D:\cocosEdit38\Creator\2.4.12\resources\app.asar\editor\lib\builder\index.ccc:1:4014
at wrapper (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\async\dist\async.js:272:20)
at next (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\async\dist\async.js:4584:24)
at D:\cocosEdit38\Creator\2.4.12\resources\app.asar\node_modules\async\dist\async.js:325:20
at D:\cocosEdit38\Creator\2.4.12\resources\app.asar\editor\core\gulp-build.ccc:1:27925
at D:\cocosEdit38\Creator\2.4.12\resources\app.asar\editor\core\gulp-build.ccc:1:5999
at Gulp. (D:\cocosEdit38\Creator\2.4.12\resources\app.asar\editor\core\gulp-build.ccc:1:29027)
at Object.onceWrapper (events.js:422:26)
at Gulp.emit (events.js:315:20)

### Steps to reproduce

1.Creator removes the webview function.
2.Export Android project.

**Comment by minggo** [comment]
Yep, it will be fixed in v2.4.13, which is in testing.

**Comment by sszyc8** [comment]
@minggo May I ask which submission information is the following

**Comment by minggo** [comment]
Sure, it is fixed in https://github.com/cocos-creator-packages/jsb-adapter/pull/374.
