### ISSUE TITLE
发布微信小游戏失败

### ISSUE THREAD

**Issue by 0Bumblebee** [cocos/cocos-engine#17445]
### Cocos Creator version

3.8.0

### System information

微信开发者工具：稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2405020) macos intel

### Issue description

**报错**
[Assets] [WeChat Dev Tool]- initialize 
[Assets] [WeChat Dev Tool]- initialize 
   
at Logger.record (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:458)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:1414)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/builtin/asset-db/dist/worker/console.ccc:1:1429)   
at Socket.<anonymous> (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/modules/platform-extensions/extensions/wechatgame/dist/hooks.ccc:1:14096)   
at Socket.emit (events.js:315:20)   
at addChunk (internal/streams/readable.js:309:12)   
at readableAddChunk (internal/streams/readable.js:284:9)   
at Socket.Readable.push (internal/streams/readable.js:223:10) 

[Assets] [WeChat Dev Tool]✔ IDE server has started, listening on http://127.0.0.1:62698 
[Assets] [WeChat Dev Tool]✔ IDE server has started, listening on http://127.0.0.1:62698 
   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:1414)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/builtin/asset-db/dist/worker/console.ccc:1:1429)   
at Socket.<anonymous> (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/modules/platform-extensions/extensions/wechatgame/dist/hooks.ccc:1:14096)   
at Socket.emit (events.js:315:20)   
at addChunk (internal/streams/readable.js:309:12)   
at readableAddChunk (internal/streams/readable.js:284:9)   
at Socket.Readable.push (internal/streams/readable.js:223:10) 

[Assets] [WeChat Dev Tool]- open IDE 
[Assets] [WeChat Dev Tool]- open IDE 
   
at Logger.record (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:458)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:1414)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/builtin/asset-db/dist/worker/console.ccc:1:1429)   
at Socket.<anonymous> (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/modules/platform-extensions/extensions/wechatgame/dist/hooks.ccc:1:14096)   
at Socket.emit (events.js:315:20)   
at addChunk (internal/streams/readable.js:309:12)   
at readableAddChunk (internal/streams/readable.js:284:9)   
at Socket.Readable.push (internal/streams/readable.js:223:10) 

[Assets] [WeChat Dev Tool]✖ open IDE 
[Assets] [WeChat Dev Tool]✖ open IDE 
   
at Logger.record (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:458)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-logger/lib/renderer.ccc:1:1414)   
at Object.error (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/builtin/asset-db/dist/worker/console.ccc:1:1429)   
at Socket.<anonymous> (/Applications/Cocos/Creator/3.8.0/CocosCreator.app/Contents/Resources/app.asar/modules/platform-extensions/extensions/wechatgame/dist/hooks.ccc:1:14096)   
at Socket.emit (events.js:315:20)   
at addChunk (internal/streams/readable.js:309:12)   
at readableAddChunk (internal/streams/readable.js:284:9)   
at Socket.Readable.push (internal/streams/readable.js:223:10) 

### Steps to reproduce

-

**Comment by minggo** [comment]
你是引擎构建成功后，使用微信开发者工具发布时遇到的问题吗？

**Comment by 0Bumblebee** [comment]
没有发布 是构建完毕后点击运行 然后弹出我的微信开发者工具之后cocos控制台报错了

在 2024年7月30日，15:39，minggo ***@***.***> 写道：

﻿

你是引擎构建成功后，使用微信开发者工具发布时遇到的问题吗？

**Comment by qiuguohua** [comment]
@0Bumblebee 我试了下，没复现，你能用个简单的工程，做个能复现的demo发我？最好构建下微信小游戏，关键是构建的配置。

**Comment by 0Bumblebee** [comment]
好的 谢谢支持，我这两天发一下 ，如果方便可否加一下微信沟通 15104905007

在 2024年8月1日，10:54，qiuguohua ***@***.***> 写道：

﻿

@0Bumblebee<https://github.com/0Bumblebee> 我试了下，没复现，你能用个简单的工程，做个能复现的demo发我？最好构建下微信小游戏，关键是构建的配置。

**Comment by yanOO1497** [comment]
这不是发布失败，这是使用微信开发者工具提供的唤起命令后，日志里的报错，如果你能正常唤起的话可以暂时忽略，工具本身经常会输出一些不影响使用的报错，这个我们没法处理，要反馈给微信。

**Comment by 0Bumblebee** [comment]
现在可以唤醒，但是仅限于唤醒微信开发者工具主页 然后cocos就报错了

在 2024年8月2日，09:56，媛媛 ***@***.***> 写道：

﻿

这不是发布失败，这是使用微信开发者工具提供的唤起命令后，日志里的报错，如果你能正常唤起的话可以暂时忽略，工具本身经常会输出一些不影响使用的报错，这个我们没法处理，要反馈给微信。

**Comment by qiuguohua** [comment]
应该是操作问题，目前换成我这边的appid，是可以正常打开的。

WeChat Dev Too等的日志都是微信开发者工具内部打印的。并不是引擎打印的。
