### ISSUE TITLE
collide Events needs rigidbody in Cocos 3.8x but dont need in Cocos 3.7.4

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17541]
### Cocos Creator version

3.8.x

### System information

All

### Issue description

Cocos Engine update from 3.7.4 to 3.8.x , then the collide event changed. normally it will trigger the collision events ,when it has component of colliders. but after 3.8x, it not only needs collider component but also the rigidboy. here is picture of the differences:
![17234518582999](https://github.com/user-attachments/assets/39721830-db9f-40e4-b069-a6fc9cdeb341)

### Relevant error log output

 [PreviewInEditor] Cannot read property 'enabledContactListener' of null
TypeError: Cannot read property 'enabledContactListener' of null
at PhysicsContact.emit (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:194408:21)
at PhysicsContactListener._onPreSolve [as _PreSolve] (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:194831:13)
at PhysicsContactListener.PreSolve (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:277145:18)
at b2PolygonAndCircleContact.Update (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\node_modules\@cocos\box2d\build\box2d\box2d.umd.js:11829:1)
at b2ContactManager.step [as Collide] (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\node_modules\@cocos\box2d\build\box2d\box2d.umd.js:12487:1)
at b2World.Step (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\node_modules\@cocos\box2d\build\box2d\box2d.umd.js:19595:27)
at b2PhysicsWorld.step (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:194619:23)
at PhysicsSystem2D.postUpdate (C:\ProgramData\cocos\editors\Creator\3.8.3\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:198074:31)
at

### Steps to reproduce

none

### Minimal reproduction project

[HaoBeginCocosProject.zip](https://github.com/user-attachments/files/16621892/HaoBeginCocosProject.zip)

**Comment by minggo** [comment]
It is reverted by https://github.com/cocos/cocos-engine/pull/15564. And i think it also reverted https://github.com/cocos/cocos-engine/pull/14102 the by mistake, so i will fix it.

**Comment by tangkaikk** [comment]
> It is reverted by #15564. And i think it also reverted #14102 the by mistake, so i will fix it.

Tks in advance.

**Comment by minggo** [comment]
I think it is fixed in https://github.com/cocos/cocos-engine/pull/17344.
