### ISSUE TITLE
抖音小游戏 线上版本 updateUVs() 方法报错.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17685]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

错误信息: 
at requestAnimationFrame callback Cannot read properties of null (reading '0')
错误的调用栈: 

<img width="437" alt="image" src="https://github.com/user-attachments/assets/6ce3687c-af56-417f-a504-52eb7923f63e">

抖音小游戏 安卓和ios都有类似错误.
同样是 我们开发者无能为力的  cocos内部错误. 
且 开发环境无法重现,  微信小游戏也不存在. 只有抖音有. 涉及到的用户非常多.

看错误好像是 一个渲染组件 isValid = true  (如果不是true 应该不会进入渲染流程) , 但是它的uv数据没了.

(这也不是一个新错误. 很早之前就有了, 只是当时我们没重视.) 

### Steps to reproduce

如上

**Comment by minggo** [comment]
这种没法重现，而且堆栈是不可阅读的情况下的报错没有什么意义。

**Comment by finscn** [comment]
> 这种没法重现，而且堆栈是不可阅读的情况下的报错没有什么意义。

目前我可以分析出个错误 是因为部分     updateUVs (sprite: Sprite)  方法只判断了 spriteFrame 是否存在 没有判断 spriteFrame 是否有效引起的.

比如文件 cocos/2d/assembler/sprite/simple.ts : 
```ts

    updateUVs (sprite: Sprite) {
        if (!sprite.spriteFrame) return;
        const renderData = sprite.renderData!;
        const vData = renderData.chunk.vb;
        const uv = sprite.spriteFrame.uv;
        vData[3] = uv[0];
        vData[4] = uv[1];
        vData[12] = uv[2];
        vData[13] = uv[3];
        vData[21] = uv[4];
        vData[22] = uv[5];
        vData[30] = uv[6];
        vData[31] = uv[7];
    },

```
看方法内的第一行,  sprite.spriteFrame 可能不为空, 但是 sprite.spriteFrame 可能还没有初始化或者已经被销毁.
uv不存在.
下面有用到 uv[0] , 也正好对应了上面报错信息里的 `Cannot read properties of null (reading '0')`

类似的还有  cocos/2d/assembler/sprite/sliced.ts .


希望此处的判断能够再严格些.
比如用  `if (!cc.isValid(sprite.spriteFrame)) return;` 来做判断.

**Comment by finscn** [comment]
至于为什么 抖音有这个问题 微信没有.  我觉得可能是在 场景切换时 的某些时序不一致 (类似问题不止一处).

比如 这里提到的这个问题  https://github.com/cocos/cocos-engine/issues/17062  (只是用来举例 和本帖的问题无关)

A环境下 需要延迟一帧才行,  B环境下不需要延迟 .
 如果B延迟也没什么问题, 只是单纯的延迟了一下而已, 
那么为了确保一致性, 就应该让 A B都延迟.

**Comment by longchuan** [comment]
这个可能是你动画做的有问题

**Comment by finscn** [comment]
> 这个可能是你动画做的有问题

动画并不是总是出这个错误啊. 一般是游戏场景切换 时. spine动画还能影响cocos场景切换?
动画用第三方播放器播放也都没问题.

**Comment by finscn** [comment]
@minggo 我简单测试了一下 用 `cc.isValid()`  是ok的.

**Comment by dexyr** [comment]
I would like to contribute some more information on a similar (the same?) issue that I experienced. I received a similar error in the console. I'm hesitant to call it a bug, since it depends on how the program is written. However, the issue doesn't have parity on preview and native builds, which makes it frustrating to debug; ideally it should cause an error on all platforms or none.

### Cocos Creator Version
3.8.7~3.8.8

### System Information
Development Platforms
- Windows 11
- Mac

Target Platforms
- Android
- iOS

### Issue Description
When
- using `Asset.addRef()`, and `Asset.decRef()` to manage resources
- `Asset.decRef()` is called in the `onDestroy()` method of the component
- the reference count of an `Asset` reaches 0 and then is incremented around the same time (same frame?)

On the browser preview and in the simulator, there is no issue, but on native builds this will throw an error if `addRef()` is not called immediately in the callback of the `AssetManager.Bundle.load()` function.

### Relevant error log Output
It only errors in native builds, so the log output is likely unusable, but here it is.

```
17:39:35 [ERROR]: [ERROR] file C:/ProgramData/cocos/editors/Creator/3.8.8/resources/resources/3d/engine/native/cocos/application/CocosApplication.cpp: line 173 
2026-02-10 17:39:35.744 13129-13146 Cocos                   ref.count.test                       E  17:39:35 [ERROR]: 
                                                                                                    Uncaught Exception:
                                                                                                     - location :  src/cocos-js/cc.d0deb.js:1:759598: 
2026-02-10 17:39:35.744 13129-13146 Cocos                   ref.count.test                       E  System.register([],(function(t,e){"use strict";return{execute:function(){function i(t,e,i,s){i&&Object.defineProperty(t,e,{enumerable:i.enumerable,configurable:i.configurable,writable:i.writable,value:i.initializer?i.initializer.call(s):void 0})}function s(t,e,i,s,n){var r={};return Object.keys(s).forEach((function(t){r[t]=s[t]})),r.enumerable=!!r.enumerable,r.configurable=!!r.configurable,("value"in r||r.initializer)&&(r.writable=!0),r=i.slice().reverse().reduce((function(i,s){return s(t,e,i)||i}),r),n&&void 0!==r.initializer&&(r.value=r.initializer?r.initializer.call(n):void 0,r.initializer=void 0),void 0===r.initializer&&(Object.defineProperty(t,e,r),r=null),r}function n(t,e){const i="undefined"==typeof window?global:window;return void 0===i[t]?i[t]=e:i[t]}t({BitMask:he,CCClass:pi,Enum:ue,Eventify:Lo,WorldNode3DToLocalNodeUI:la,WorldNode3DToWorldNodeUI:ca,__checkObsoleteInNamespace__:function(t){return ot||(ot="undefined"==typeof Proxy?{}:new Proxy(t,{get:(t,e,i)=>(rt(e),Reflect.get(t,e,i))})),ot},__checkObsolete__:function(t){for(let e of t)rt(e)},_resetDebugSetting:P,absMax:Xi,absMaxComponent:qi,applyMixins:Xu,approx:Bi,assert:B,assertID:j,assertIsNonNullable:function(){},assertIsTrue:function(){},assertsArrayIndex:le,bezier:Nc,bezierByTime:Hc,binarySearch:function(t,e){return ja(t,e,0)},binarySearchBy:function(t,e,i){let s=0,n=t.length-1,r=n>>>1;for(;s<=n;r=s+n>>>1){const o=t[r];if(i(o,e)<0)n=r-1;else{if(!(i(o,e)>0))return r;s=r+1}}return~s},binarySearchEpsilon:ja,ccenum:me,clamp:Ei,clamp01:Pi,color:Fs,computeRatioByType:gk,debug:E,debugID:L,deprecateModuleExportedName:nt,deserialize:Hf,enumerableProps:Yi,equals:Ii,error:I,errorID:U,find:fx,flattenCodeArray:qu,floatToHalf:Ji,formerlySerializedAs:Sh,fragmentText:$D,getBaselineOffset:ID,getEnglishWordPartAtFirst:XD,getEnglishWordPartAtLast:YD,getError:W,getPathFromRoot:function(t,e){let i=t,s="";for(;null!==i&&i!==e;)s=`${i.name}/${s}`,i=i.parent;return s.slice(0,-1)},getSerializationMetadata:function(t){return t[yh]},getSymbolAt:GD,getSymbolCodeAt:jD,getSymbolLength:UD,getWorldTransformUntilRoot:function(t,e,i){for(bn.identity(i);t!==e;)bn.fromRTS(iG,t.rotation,t.position,t.scale),bn.multiply(i,iG,i),t=t.parent;return i},halfToFloat:Zi,instantiate:WG,inverseLerp:Wi,isCCClassOrFastDefined:fi,isCCObject:Io,isDisplayStats:q,isEnglishWordPartAtFirst:function(t){return LD.test(t)},isEnglishWordPartAtLast:function(t){return ND.test(t)},isUnicodeCJK:VD,isUnicodeSpace:kD,isValid:Bo,lerp:Mi,loadWasmModuleSpine:g5,log:C,logID:F,mat4:xn,murmurhash2_32_gc:Gu,nextPow2:Gi,pingPong:Hi,pseudoRandom:ki,pseudoRandomRange:zi,pseudoRandomRangeInt:Ui,quat:ln,random:Fi,randomRange:Li,randomRangeInt:Vi,rect:Hn,repeat:ji,safeMeasureText:zD,sampleAnimationCurve:fk,setDefaultLogTimes:function(t){t>0&&(tt=t)},setDisplayStats:X,setPropertyEnumType:ei,setPropertyEnumTypeOnAttrs:ii,setRandGenerator:Ni,shift:function(t,e,i){if(le(t,e),le(t,i),e===i)return t;const s=t[e];if(e<i)for(let s=e+1;s<=i;++s)t[s-1]=t[s];else for(let s=e;s!==i;--s)t[s]=t[s-1];return t[i]=s,t},size:zn,toDegree:Ri,toRadian:Oi,tween:v8,tweenUtil:x8,v2:Ln,v3:Is,v4:ds,warn:D,warnID:k}),n("CC_WECHAT",!1),n("CC_XIAOMI",!1),n("CC_ALIPAY",!1),n("CC_BYTEDANCE",!1),n("CC_OPPO",!1),n("CC_VIVO",!1),n("CC_HUAWEI",!1),n("CC_MIGU",!1),n("CC_HONOR",!1),n("CC_COCOS_RUNTIME",!1);n("CC_EDITOR",!1),n("CC_PREVIEW",!1),n("CC_BUILD",!0),n("CC_TEST",!1),n("CC_DEBUG",!1),n("CC_DEV",!1),n("CC_MINIGAME",!1),n("CC_RUNTIME_BASED",!1),n("CC_SUPPORT_JIT",!0),n("CC_JSB",!0);const r="undefined"==typeof window?global:window,o=t("cclegacy",{_global:r}),a=o;o.internal={};const h=t("VERSION","3.8.8");r.CocosEngine=a.ENGINE_VERSION=h,r.cc=a;const l=void 0!==globalThis.jsb&&void 0!==jsb.window?jsb.window:globalThis;r.ccwindow=l;function c(t,e){return t^(t^e)&-(t<e)}function u(t){let e,i;return e=(t>65535)<<4,i=((t>>>=e)>255)<<3,e|=i,i=((t>>>=i)>15)<<2,e|=i,i=((t>>>=i)>3)<<1,e|=i,e|(t>>>=i)>>1}function _(t){return 16843009*((t=(858993459&(t-=t>>>1&1431655765))+(t>>>2&858
2026-02-10 17:39:35.756 13129-13146 Cocos                   ref.count.test                       E  17:39:35 [ERROR]: JS: src/cocos-js/cc.d0deb.js:1:759598: 
2026-02-10 17:39:35.756 13129-13146 Cocos                   ref.count.test                       E  System.register([],(function(t,e){"use strict";return{execute:function(){function i(t,e,i,s){i&&Object.defineProperty(t,e,{enumerable:i.enumerable,configurable:i.configurable,writable:i.writable,value:i.initializer?i.initializer.call(s):void 0})}function s(t,e,i,s,n){var r={};return Object.keys(s).forEach((function(t){r[t]=s[t]})),r.enumerable=!!r.enumerable,r.configurable=!!r.configurable,("value"in r||r.initializer)&&(r.writable=!0),r=i.slice().reverse().reduce((function(i,s){return s(t,e,i)||i}),r),n&&void 0!==r.initializer&&(r.value=r.initializer?r.initializer.call(n):void 0,r.initializer=void 0),void 0===r.initializer&&(Object.defineProperty(t,e,r),r=null),r}function n(t,e){const i="undefined"==typeof window?global:window;return void 0===i[t]?i[t]=e:i[t]}t({BitMask:he,CCClass:pi,Enum:ue,Eventify:Lo,WorldNode3DToLocalNodeUI:la,WorldNode3DToWorldNodeUI:ca,__checkObsoleteInNamespace__:function(t){return ot||(ot="undefined"==typeof Proxy?{}:new Proxy(t,{get:(t,e,i)=>(rt(e),Reflect.get(t,e,i))})),ot},__checkObsolete__:function(t){for(let e of t)rt(e)},_resetDebugSetting:P,absMax:Xi,absMaxComponent:qi,applyMixins:Xu,approx:Bi,assert:B,assertID:j,assertIsNonNullable:function(){},assertIsTrue:function(){},assertsArrayIndex:le,bezier:Nc,bezierByTime:Hc,binarySearch:function(t,e){return ja(t,e,0)},binarySearchBy:function(t,e,i){let s=0,n=t.length-1,r=n>>>1;for(;s<=n;r=s+n>>>1){const o=t[r];if(i(o,e)<0)n=r-1;else{if(!(i(o,e)>0))return r;s=r+1}}return~s},binarySearchEpsilon:ja,ccenum:me,clamp:Ei,clamp01:Pi,color:Fs,computeRatioByType:gk,debug:E,debugID:L,deprecateModuleExportedName:nt,deserialize:Hf,enumerableProps:Yi,equals:Ii,error:I,errorID:U,find:fx,flattenCodeArray:qu,floatToHalf:Ji,formerlySerializedAs:Sh,fragmentText:$D,getBaselineOffset:ID,getEnglishWordPartAtFirst:XD,getEnglishWordPartAtLast:YD,getError:W,getPathFromRoot:function(t,e){let i=t,s="";for(;null!==i&&i!==e;)s=`${i.name}/${s}`,i=i.parent;return s.slice(0,-1)},getSerializationMetadata:function(t){return t[yh]},getSymbolAt:GD,getSymbolCodeAt:jD,getSymbolLength:UD,getWorldTransformUntilRoot:function(t,e,i){for(bn.identity(i);t!==e;)bn.fromRTS(iG,t.rotation,t.position,t.scale),bn.multiply(i,iG,i),t=t.parent;return i},halfToFloat:Zi,instantiate:WG,inverseLerp:Wi,isCCClassOrFastDefined:fi,isCCObject:Io,isDisplayStats:q,isEnglishWordPartAtFirst:function(t){return LD.test(t)},isEnglishWordPartAtLast:function(t){return ND.test(t)},isUnicodeCJK:VD,isUnicodeSpace:kD,isValid:Bo,lerp:Mi,loadWasmModuleSpine:g5,log:C,logID:F,mat4:xn,murmurhash2_32_gc:Gu,nextPow2:Gi,pingPong:Hi,pseudoRandom:ki,pseudoRandomRange:zi,pseudoRandomRangeInt:Ui,quat:ln,random:Fi,randomRange:Li,randomRangeInt:Vi,rect:Hn,repeat:ji,safeMeasureText:zD,sampleAnimationCurve:fk,setDefaultLogTimes:function(t){t>0&&(tt=t)},setDisplayStats:X,setPropertyEnumType:ei,setPropertyEnumTypeOnAttrs:ii,setRandGenerator:Ni,shift:function(t,e,i){if(le(t,e),le(t,i),e===i)return t;const s=t[e];if(e<i)for(let s=e+1;s<=i;++s)t[s-1]=t[s];else for(let s=e;s!==i;--s)t[s]=t[s-1];return t[i]=s,t},size:zn,toDegree:Ri,toRadian:Oi,tween:v8,tweenUtil:x8,v2:Ln,v3:Is,v4:ds,warn:D,warnID:k}),n("CC_WECHAT",!1),n("CC_XIAOMI",!1),n("CC_ALIPAY",!1),n("CC_BYTEDANCE",!1),n("CC_OPPO",!1),n("CC_VIVO",!1),n("CC_HUAWEI",!1),n("CC_MIGU",!1),n("CC_HONOR",!1),n("CC_COCOS_RUNTIME",!1);n("CC_EDITOR",!1),n("CC_PREVIEW",!1),n("CC_BUILD",!0),n("CC_TEST",!1),n("CC_DEBUG",!1),n("CC_DEV",!1),n("CC_MINIGAME",!1),n("CC_RUNTIME_BASED",!1),n("CC_SUPPORT_JIT",!0),n("CC_JSB",!0);const r="undefined"==typeof window?global:window,o=t("cclegacy",{_global:r}),a=o;o.internal={};const h=t("VERSION","3.8.8");r.CocosEngine=a.ENGINE_VERSION=h,r.cc=a;const l=void 0!==globalThis.jsb&&void 0!==jsb.window?jsb.window:globalThis;r.ccwindow=l;function c(t,e){return t^(t^e)&-(t<e)}function u(t){let e,i;return e=(t>65535)<<4,i=((t>>>=e)>255)<<3,e|=i,i=((t>>>=i)>15)<<2,e|=i,i=((t>>>=i)>3)<<1,e|=i,e|(t>>>=i)>>1}function _(t){return 16843009*((t=(858993459&(t-=t>>>1&1431655765))+(t>>>2&858993459))+(t>>>4)&252645135
2026-02-10 17:39:35.756 13129-13146 Cocos                   ref.count.test                       E  
2026-02-10 17:39:35.763 13129-13146 Cocos                   ref.count.test                       E  17:39:35 [ERROR]: [SE_ERROR]  (C:/ProgramData/cocos/editors/Creator/3.8.8/resources/resources/3d/engine/native/cocos/bindings/jswrapper/v8/Object.cpp, 821): Invoking function (0x7471f06a9a50) failed!
```

### Steps to Reproduce
Same conditions as in the Issue Description.

### Minimal Reproduction Project
```ts
class Anything extends Component {
  @property(Node)
  spriteAnchor: Node;  

  sprite: Sprite | null = null;

  /* load sprite -> await -> add ref & use */
  /* this doesn't cause errors in the browser preview or simulator */
  async recreateSprite() {
    this.sprite?.destroy();

    const node = new Node();
    node.addComponent(UITransform);

    const sprite = node.addComponent(Sprite);

    const frame = await new Promise<SpriteFrame>((resolve) => {
      resources.load('some_sprite_in_resource_folder/spriteFrame', SpriteFrame, (error, data) => {
        if (error) {
          throw error;
        }

        /* if data.addRef() were called here instead, it would not crash */
        // data.addRef();

        resolve(data);
      });
    });

    frame.addRef();
    console.log('[addRef] current refCount:', frame.refCount);

    sprite.spriteFrame = frame;

    /* this happens even when onDestroy is properly declared in a custom component */
    sprite.onDestroy = () => {
      sprite.spriteFrame.decRef();
      console.log('[decRef] current refCount:', this.sprite.spriteFrame.refCount);
    };

    sprite.node.setParent(this.spriteAnchor);
    this.sprite = sprite;
}
```

In the actual test project, I have two buttons, one which calls `addRef()` in the `load()` callback, and one which calls it after awaiting the promise.

In the browser and simulator, clicking either button logs this.
```
[addRef] current refCount: 1
[decRef] current refCount: 0
[addRef] current refCount: 1
[decRef] current refCount: 0
[addRef] current refCount: 1
[decRef] current refCount: 0
[addRef] current refCount: 1
```

However, on an Android build, clicking the button that calls `addRef()` in the `load()` callback logs this, and clicking the button that calls `addRef()` after awaiting the promise causes the error / crash.

```
2026-02-10 17:57:24.144 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [addRef] current refCount: 1
2026-02-10 17:57:24.317 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [decRef] current refCount: 1
2026-02-10 17:57:24.370 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [addRef] current refCount: 1
2026-02-10 17:57:24.484 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [decRef] current refCount: 1
2026-02-10 17:57:24.532 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [addRef] current refCount: 1
2026-02-10 17:57:24.661 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [decRef] current refCount: 1
2026-02-10 17:57:24.723 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [addRef] current refCount: 1
2026-02-10 17:57:24.837 13429-13447 Cocos                   ref.count.test                       D  17:57:24 [DEBUG]: JS: [decRef] current refCount: 1
```

I can provide a complete minimal reproduction project if necessary, but I think the code snippet should explain the reproduction steps fairly well.

**Comment by dav-sea** [comment]
In some cases related to the release and loading of resources (including the same ones),
errors in accessing non-existent objects occur in the internal logic of the rendering engine,
for example:
```
    simple.ts:200 Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at e.updateUVs (simple.ts:200:31)
    at i._updateUVs (sprite.ts:687:29)
    at i.OnEnable (sprite.ts:497:18)
```

Platforms: `web-mobile`, `android`
CC version: `3.8.8`

In our case, as a workaround, we had to use a custom version of the engine, with some modifications in `cocos/2d/assembler/sprite/simple.ts`

The essence of the modification boils down to adding a null check in some places.

Our workaround: https://github.com/snbstudio/custom-cocos-engine/commit/bcf9bbe71da0ec747b220b60feef36f00a5434b4

**Comment by ShadeWorld** [comment]
应该是用了还没加载完成或者已经释放的资源
