### ISSUE TITLE
在"editing-did-ended"事件中摧毁EditBox所在节点的间接父节点时出错

### ISSUE THREAD

**Issue by mcube-12139** [cocos/cocos-engine#17890]
### Cocos Creator version

3.8.4

### System information

Windows 10 Editor

### Issue description

在EditBox组件所在节点的`editing-did-ended`事件中摧毁其间接父节点（爷节点）时，产生错误，似乎是一个引擎内部错误。
非必现，但重现概率较高，原因不明。

### Relevant error log output

```
[PreviewInEditor] Cannot read property 'length' of null 
TypeError: Cannot read property 'length' of null 
    at Node._updateSiblingIndex (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:45101:46) 
    at eval (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:97958:18) 
    at Map.forEach (<anonymous>) 
    at _sortSiblings (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:97956:45) 
    at Director.emit (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:137495:19) 
    at Director.tick (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:17660:20) 
    at Game._updateCallback (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:19321:22) 
    at updateCallback (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:78612:20) 
    at sentryWrapped (C:\ProgramData\cocos\editors\Creator\3.8.4\resources\app.asar\node_modules\src\helpers.ts:100:17) 
```

### Steps to reproduce

1. 新建场景。
2. 在Canvas节点下创建节点A。
3. 在节点A下创建节点B。
4. 在节点B下创建UI Component - EditBox节点。
5. 创建TypeScript组件`NodeControl`，写入如下代码：
```typescript
import { _decorator, Component, EditBox } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('NodeControl')
export class NodeControl extends Component {
    @property(EditBox)
    editBox: EditBox;

    start() {
        this.editBox.node.on("editing-did-ended", (editBox: EditBox) => {
            this.node.destroy();
        }, this);
    }
}
```
6. 附加`NodeControl`组件到节点A上。
7. 在Inspector中将EditBox节点拖入`editBox`属性。
8. 保存，在编辑器中运行预览该场景，在输入框中输入任意内容，然后按下Enter键。

### Minimal reproduction project

[editbox-bug.zip](https://github.com/user-attachments/files/17825480/editbox-bug.zip)

**Comment by longchuan** [comment]
改为`this.node.removeFromParent();`

**Comment by ghost** [comment]
```ts
public static _sortSiblings (): void {
        UITransform.priorityChangeNodeMap.forEach((node, ID): void => {
            UITransform._sortChildrenSibling(node);
            node._updateSiblingIndex();
            node.emit('childrenSiblingOrderChanged');
        });
        UITransform.priorityChangeNodeMap.clear();
    }

```
UITransform.priorityChangeNodeMap保存着已经调用destroy的节点

**Comment by minggo** [comment]
@mcube-12139 我用 3.8.4、3.8.5 都无法重现。

**Comment by minggo** [comment]
哦哦，我没有用编辑器预览，用的是浏览器预览。浏览器预览是没问题的。
