### ISSUE TITLE
UITransform._sortSiblings函数中访问已被销毁的节点导致报错

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#18040]
### Cocos Creator version

3.8.4

### System information

macOS 14.4.1 Editor

### Issue description

子节点添加UITransform组件之后将父节点添加到UITransform.priorityChangeNodeMap，父节点调用destroy。在UITransform._sortSiblings函数中会访问到已经被销毁的父节点

### Relevant error log output

```
[PreviewInEditor] Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
at Node._updateSiblingIndex (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:52923:46)
at eval (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:108395:18)
at Map.forEach (<anonymous>)
at _sortSiblings (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:108393:45)
at Director.emit (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:143934:19)
at Director.tick (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:17321:20)
at Game._updateCallback (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:16506:22)
at updateCallback (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:87087:20)
at sentryWrapped (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/src/helpers.ts:100:17)
```

### Steps to reproduce

```ts
let parent = new Node("parent");
let child = new Node("child");
child.addComponent(UITransform);
parent.addChild(child);
parent.destroy();
```

**Comment by Liuuwei** [comment]
报错信息
```
[PreviewInEditor] Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
at Node._updateSiblingIndex (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:52923:46)
at eval (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:108395:18)
at Map.forEach (<anonymous>)
at _sortSiblings (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:108393:45)
at Director.emit (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:143934:19)
at Director.tick (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:17321:20)
at Game._updateCallback (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:16506:22)
at updateCallback (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/editor/bundled/index.js:87087:20)
at sentryWrapped (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/src/helpers.ts:100:17)
```

**Comment by minggo** [comment]
最好提供 demo。虽然你提供了重现的代码，但是这些代码执行的时机和位置不同也会影响结果。

**Comment by ghost** [comment]
[demo.zip](https://github.com/user-attachments/files/18243917/demo.zip)
复现的demo，编辑器预览
