### ISSUE TITLE
Error: Channel does not exist: scene:spine-preview

### ISSUE THREAD

**Issue by jeffma** [cocos/cocos-engine#18071]
### Cocos Creator version

3.8.4

### System information

MacOS webgl

### Issue description

我移植了spine 4.2到spine-wasm，场景中skeletonData没有报错，但是spine-preview.js里面报Error: Channel does not exist: scene:spine-preview，经调试 await panel.glPreview.init({ width: panel.$.canvas.clientWidth, height: panel.$.canvas.clientHeight }); 这行报错

### Relevant error log output

[Window] init glPreview error!: Error: Channel does not exist: scene:spine-preview
at Object.sendToChannel (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-base-ipc/dist/renderer.ccc:1:2198)
at sendToChannel (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/@base/electron-base-ipc/dist/index.js:1:1194)
at GlPreview.init (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/builtin/scene/dist/preview-extends/webgl.ccc:1:1381)
at Object.update (/Users/jeffma/Workspace/cocos-engine/editor/inspector/assets/spine-preview.js:198:39)
at Object.<anonymous> (/Users/jeffma/Workspace/cocos-engine/editor/inspector/assets/spine-preview.js:396:28)
at HTMLElement.update (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/@editor/creator-ui-kit/dist/renderer.ccc:2:1614316)
at /Users/jeffma/Workspace/cocos-engine/editor/inspector/contributions/asset.js:344:43
at Array.map (<anonymous>)
at Object.update (/Users/jeffma/Workspace/cocos-engine/editor/inspector/contributions/asset.js:343:50)

### Steps to reproduce

这里是我编译出来的spine wasm 
[spine.zip](https://github.com/user-attachments/files/18220926/spine.zip)

**Comment by jeffma** [comment]
另外这个地址是我的fork:  https://github.com/originpoint-at/cocos-engine

**Comment by bofeng-song** [comment]
我目前正在进行 4.2这块的移植，不确定您这边是只更新spine源码，还有更新引擎的内容吗？
我目前的移植方式，主要修改的是spine 关联的cpp的修改；ts基本没动；可能需要等我的验证后，才能给你建议

**Comment by jeffma** [comment]
哦，目前我把4.2的类型映射过来了，目前我看bone,slot,mesh数据已经被正常debug出来了，我看大概率是altas的texture没有正确关联，引擎代码我还没有改完

**Comment by jeffma** [comment]
我对cocos engine的整体渲染流程还不熟，但是我对spine的流程很熟，我们自己项目里的wasm webgpu渲染我已经搞定了，我们现在很着急支持cocos engine，如果你们有需要我可以分担一部分工作
