### ISSUE TITLE
MacOS下 通过命令行 构建微信小游戏时报错. 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#18102]
### Cocos Creator version

3.8.4

### System information

macOS

### Issue description

错误信息如下: 
```
2024-12-31 13:11:59 - debug: // ---- build task 整理部分构建选项内数据到 settings.json ---- (300ms)


Warn: [Assets] Catch uncaughtException when build task wechatgame running
    at Object.warn (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/builtin/asset-db/dist/worker/console.ccc:1:1510)
    at NewConsole.warn (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/builtin/builder/dist/worker/console.ccc:1:2337)
    at process.<anonymous> (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/builtin/builder/dist/worker/index.ccc:1:2671)
    at process.emit (events.js:315:20)
    at process.<anonymous> (/自定义引擎目录/bin/.cache/dev/editor/loader.js:4979:21)
    at processEmit [as emit] (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/signal-exit/index.js:155:32)
    at window.onerror (electron/js2c/renderer_init.js:93:3042)
    at /Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/@sentry/src/instrument/globalError.ts:41:33
[Warn: ENOENT: no such file or directory, open '/项目目录/build/wechatgame/assets/main.js']


2024-12-31 13:11:59 - debug: run build task 整理部分构建选项内数据到 settings.json success in 300 ms√, progress: 36%

```
构建时会去找一个 3.8.x系列已经不再使用的文件 `build/wechatgame/assets/main.js`.
虽然是警告, 但是这个明显是构建流程里有错误. 希望能解决.

另外, 我们用到了自定义引擎目录 , 但是自定义引擎主要是渲染层面的一些调整 没有动构建相关的东西.

### Steps to reproduce

.

**Comment by finscn** [comment]
补充一个错误: 
```
[information] Query information: Error: GET Timeout: https://creator-api.cocos.com/information_url
    at ClientRequest.<anonymous> (/Applications/Cocos/Creator/3.8.4/CocosCreator.app/Contents/Resources/app.asar/node_modules/@editor/creator/dist/network/protected/browser/util.ccc:1:2428)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.emit (domain.js:467:12)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.emit (domain.js:467:12)
    at TLSSocket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

这个也是总出现.
