### ISSUE TITLE
创建预设被删除，使用的预设界面没有解绑定，再保存出错

### ISSUE THREAD

**Issue by wulei** [cocos/cocos-engine#1869]
我先创建一个预设，然后删除这个预设，使用预设的还是关联这这个预设，然后再点这个预设实例化出来的物体保存预设报错

```
Failed to apply "HelloWorld" because the prefab asset is missing, please save the prefab to a new asset by dragging and drop the node from Node Tree into Assets.
    at Object.applyPrefab (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/scene-utils/index.js:1:15584)
    at editor-scene.scene:apply-prefab (file:///Applications/CocosCreator.app/Contents/Resources/app.asar/editor/builtin/scene/panel/scene.js:1:10531)
    at Object.Panel._dispatch (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/panel.js:1:2211)
    at EventEmitter.ipcRenderer.on (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/ipc.js:1:3891)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

**Comment by wulei** [comment]
使用版本为Cocos Creator v1.6.0-beta.3

**Comment by jareguo** [comment]
这个报错信息不是 bug，是因为你预设都删掉了，所以没办法保存。报错信息里应该也已经包含了你需要的其它完整信息。
