### ISSUE TITLE
Error: write callback calls multiple times

### ISSUE THREAD

**Issue by acrazing** [cocos/cocos-engine#2496]
构建时发生的, 请问一下该如何解决?

错误日志:

```
2018-04-03T09:12:10.809Z - normal: Compiled project javascript file successfully
2018-04-03T09:12:10.809Z - error: Build Failed: Error: write callback called multiple times
    at DestroyableTransform.afterTransform (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:84:31)
    at DestroyableTransform._transform (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/composer.js:13:9)
    at DestroyableTransform.Transform._read (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at write (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at Async.series.t (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/core/builder.js:1:3024)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:726:13
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:264:21
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:44:16
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:723:17
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:167:37
    at Gulp.doneCallback (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/core/gulp-build.js:1:18343)
    at Gulp.Orchestrator.stop (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/orchestrator/index.js:150:9)
```

**Comment by jareguo** [comment]
请问用的是什么版本？能提供一个示例项目吗？

**Comment by acrazing** [comment]
1.9.0, 项目内容太多了, 似乎提供不了

**Comment by jareguo** [comment]
那我们也看不出是什么问题啊…… 有点像是压缩脚本所用的 uglify 的 bug，可能是特殊的 js 语法触发的。

**Comment by acrazing** [comment]
应该是sourcemap的问题, 我去掉选项就好了, 但是我没法debug, 不知道是什么原因导致的.

**Comment by jareguo** [comment]
嗯…… 先关掉吧，应该是特殊项目引起的，没有 demo 的话我们查不了，抱歉哈
