### ISSUE TITLE
命令行发布项目，项目界面打开后不会自动继续，需要手动打开构建界面并点击构建按钮

### ISSUE THREAD

**Issue by gyt0412** [cocos/cocos-engine#2560]
命令行发布项目，项目界面打开后不会自动继续，需要手动打开构建界面并点击构建按钮
比如执行：D:/CocosCreator/CocosCreator.exe --path "E:/cocos/first/start_project"
命令行执行到以下这个地方：
===== Initializing Editor =====
arguments:
  --path
  E:/cocos/first/start_project

[3408] Load ~/.CocosCreator/settings.json
[3408] checking language setting...
[3408] Language: zh
[3408] protocol editor-framework registered
[3408] protocol app registered
[3408] protocol theme registered
[3408] protocol profile registered
[3408] protocol packages registered
[3408] protocol unpack registerred
[3408] protocol disable-commonjs registerred
[3408] failed to connect login server due to request timeout
[3408] Check project E:\cocos\first\start_project
[3408] Initializing Cocos2d
Initializing engine extends
[3408] Initializing Asset Database
[3408] protocol uuid registerred
[3408] protocol db registerred
[3408] protocol thumbnail registerred
[3408] Loading editor/builtin packages
[3408] anysdk loaded
[3408] assets loaded
[3408] builder loaded
[3408] hierarchy loaded
[3408] inspector loaded
[3408] keystore loaded
[3408] node-library loaded
[3408] package-asset loaded
[3408] preferences loaded
[3408] project-exporter loaded
[3408] project-importer loaded
[3408] project-settings loaded
[3408] ui-kit loaded
[3408] ui-grid loaded
[3408] scene loaded
[3408] sprite-editor loaded
[3408] store loaded
[3408] timeline loaded
[3408] Loading builtin packages
[3408] asset-db-debugger loaded
[3408] color-picker loaded
[3408] console loaded
[3408] package-manager loaded
[3408] sdkbox loaded
[3408] tester loaded
[3408] ui-kit-preview-extra loaded
[3408] ui-kit-preview loaded
[3408] ui-tree loaded
[3408] Initializing project E:\cocos\first\start_project
[3408] Loading packages
[3408] Watching packages
[3408] Run Application
[3408] preview server running at http://localhost:7457
init QuickCompiler: 186.096ms
no valid user ID
[3408] 1.6.1

到这里，主界面已经打开，但不会继续执行了。如果手动选择项目-构建发布-构建，才会继续执行直到结束。如下：

===== Initializing Editor =====
arguments:
  --path
  E:/cocos/first/start_project

[3408] Load ~/.CocosCreator/settings.json
[3408] checking language setting...
[3408] Language: zh
[3408] protocol editor-framework registered
[3408] protocol app registered
[3408] protocol theme registered
[3408] protocol profile registered
[3408] protocol packages registered
[3408] protocol unpack registerred
[3408] protocol disable-commonjs registerred
[3408] failed to connect login server due to request timeout
[3408] Check project E:\cocos\first\start_project
[3408] Initializing Cocos2d
Initializing engine extends
[3408] Initializing Asset Database
[3408] protocol uuid registerred
[3408] protocol db registerred
[3408] protocol thumbnail registerred
[3408] Loading editor/builtin packages
[3408] anysdk loaded
[3408] assets loaded
[3408] builder loaded
[3408] hierarchy loaded
[3408] inspector loaded
[3408] keystore loaded
[3408] node-library loaded
[3408] package-asset loaded
[3408] preferences loaded
[3408] project-exporter loaded
[3408] project-importer loaded
[3408] project-settings loaded
[3408] ui-kit loaded
[3408] ui-grid loaded
[3408] scene loaded
[3408] sprite-editor loaded
[3408] store loaded
[3408] timeline loaded
[3408] Loading builtin packages
[3408] asset-db-debugger loaded
[3408] color-picker loaded
[3408] console loaded
[3408] package-manager loaded
[3408] sdkbox loaded
[3408] tester loaded
[3408] ui-kit-preview-extra loaded
[3408] ui-kit-preview loaded
[3408] ui-tree loaded
[3408] Initializing project E:\cocos\first\start_project
[3408] Loading packages
[3408] Watching packages
[3408] Run Application
[3408] preview server running at http://localhost:7457
init QuickCompiler: 186.096ms
no valid user ID
[3408] 1.6.1
[3408] Error: { Error: connect ETIMEDOUT 211.151.21.150:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '211.151.21.150',
  port: 443 }
    at D:\CocosCreator\resources\app.asar\share\login\lib\user.js:1:1365
    at ClientRequest.Https.request.on.e (D:\CocosCreator\resources\app.asar\shar
e\login\lib\network.js:1:797)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
{ Error: connect ETIMEDOUT 203.208.40.130:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '203.208.40.130',
  port: 443 }
{ Error: connect ETIMEDOUT 203.208.40.128:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '203.208.40.128',
  port: 443 }
no valid user ID
[3408] Start building with options : {
  "androidStudio": true,
  "apiLevel": "",
  "appABIs": [],
  "appKey": "",
  "appSecret": "",
  "buildPath": "E:\\cocos\\first\\start_project\\build",
  "debug": false,
  "dest": "E:\\cocos\\first\\start_project\\build\\web-mobile",
  "excludedModules": [],
  "includeAnySDK": false,
  "includeEruda": false,
  "includeSDKBox": false,
  "inlineSpriteFrames": true,
  "inlineSpriteFrames_native": true,
  "md5Cache": false,
  "mergeStartScene": false,
  "oauthLoginServer": "",
  "optimizeHotUpdate": false,
  "orientation": {
    "landscapeLeft": true,
    "landscapeRight": true,
    "portrait": false,
    "upsideDown": false
  },
  "packageName": "org.cocos2d.start_project",
  "platform": "web-mobile",
  "previewHeight": 720,
  "previewWidth": 1280,
  "privateKey": "",
  "renderMode": "0",
  "scenes": [
    "14a819a7-a283-45b8-a1af-12d003028b2c",
    "ff055547-5468-49d5-8b96-158d0b1eb0ea",
    "5411b9ed-32c9-4336-8389-2aff6020e2f8"
  ],
  "sourceMaps": false,
  "startScene": "14a819a7-a283-45b8-a1af-12d003028b2c",
  "template": "link",
  "title": "start_project",
  "useDebugKeystore": true,
  "vsVersion": "auto",
  "webOrientation": "auto",
  "project": "E:\\cocos\\first\\start_project",
  "projectName": "start_project",
  "debugBuildWorker": false
}
[3408] Building E:\cocos\first\start_project
[3408] Destination E:\cocos\first\start_project\build\web-mobile
[3408] Delete E:\cocos\first\start_project\build\web-mobile\res/**/*
[3408] Delete E:\cocos\first\start_project\build\web-mobile\src/*/
[3408] Compiled project javascript file successfully
[3408] Start building assets
[3408] Start spawn build-worker
[3408] Finish spawn build-worker
[3408] Start init build-worker
[3408] 1.6.1
[3408] Finish init build-worker
[3408] Start build-assets in worker
[3408] Finish build-assets in worker
[3408] Finish building assets
queryAssets: 10.021ms
[3408] Start building raw assets
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\audi
o\jump.mp3 to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\audio
\jump.mp3
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\audi
o\score.mp3 to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\audi
o\score.mp3
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\mika
do_outline_shadow.png to E:\cocos\first\start_project\build\web-mobile\res\raw-a
ssets\mikado_outline_shadow.png
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\text
ures\PurpleMonster.png to E:\cocos\first\start_project\build\web-mobile\res\raw-
assets\textures\PurpleMonster.png
[3408] Start building plugin scripts
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\tex
tures\PurpleMonster.png to E:\cocos\first\start_project\build\web-mobile\res\raw
-assets\textures\PurpleMonster.png
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\text
ures\background.jpg to E:\cocos\first\start_project\build\web-mobile\res\raw-ass
ets\textures\background.jpg
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\mik
ado_outline_shadow.png to E:\cocos\first\start_project\build\web-mobile\res\raw-
assets\mikado_outline_shadow.png
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\text
ures\btn_play.png to E:\cocos\first\start_project\build\web-mobile\res\raw-asset
s\textures\btn_play.png
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\tex
tures\background.jpg to E:\cocos\first\start_project\build\web-mobile\res\raw-as
sets\textures\background.jpg
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\text
ures\ground.png to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\
textures\ground.png
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\tex
tures\btn_play.png to E:\cocos\first\start_project\build\web-mobile\res\raw-asse
ts\textures\btn_play.png
[3408] [build-raw-assets] Start copying E:\cocos\first\start_project\assets\text
ures\star.png to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\te
xtures\star.png
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\aud
io\jump.mp3 to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\audi
o\jump.mp3
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\aud
io\score.mp3 to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\aud
io\score.mp3
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\tex
tures\ground.png to E:\cocos\first\start_project\build\web-mobile\res\raw-assets
\textures\ground.png
[3408] [build-raw-assets] Finish copying E:\cocos\first\start_project\assets\tex
tures\star.png to E:\cocos\first\start_project\build\web-mobile\res\raw-assets\t
extures\star.png
[3408] Finish building raw assets
[3408] Generating html from D:\CocosCreator\resources\static\build-templates\sha
res\browser_not_support.html
[3408] Generating html from D:\CocosCreator\resources\static\build-templates\sha
res\index.html
[3408] Generating main.js from D:\CocosCreator\resources\static\build-templates\
shares\main.js
[3408] Built to "E:\cocos\first\start_project\build\web-mobile" successfully

另外构建过程中，会不断有这样的报错（但不影响构建）：
Error: { Error: connect ETIMEDOUT 211.151.21.150:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '211.151.21.150',
  port: 443 }
    at D:\CocosCreator\resources\app.asar\share\login\lib\user.js:1:1365
    at ClientRequest.Https.request.on.e (D:\CocosCreator\resources\app.asar\shar
e\login\lib\network.js:1:797)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

还有，构建结束后，命令行不会自动退出，打开的界面也不会自动关闭。

总结下，就是三个问题：
1、使用命令行构建项目时，不能自动执行至结束，需要手动干预
2、构建过程中会有网络连接超时之类的报错
3、构建结束后不会自动关闭主界面，命令行进程也并没有退出。

以上几个问题希望修复一下，或者提供下解决办法，万分感谢！

### Creator version?（版本号）
1.9.0

### Affected platform?（受影响的平台）
Windows Editor 

### Demo project?（demo 项目）
任意项目都可以

**Comment by jareguo** [comment]
请参考 http://docs.cocos.com/creator/manual/zh/publish/publish-in-command-line.html ，使用正确的构建参数

**Comment by gyt0412** [comment]
谢谢回复，现在可以了。原因就是我省略了那些参数，我以为那些参数是可以省略的，因为文档中有一句：这里会使用 Creator 中构建面板当前的参数来作为默认构建参数，如果指定了其他参数，则会使用指定的参数来覆盖默认参数。
希望文档可以描述清楚一点以免误导吧。
两次感谢！

**Comment by jareguo** [comment]
麻烦 @xunyi0 按照 gyt0412 反馈的部分更新下文档，避免误导用户。

**Comment by xunyi0** [comment]
@gyt0412 请问一下你忽略了哪些参数？
