### ISSUE TITLE
微信开发平台中audio销毁导致的报错

### ISSUE THREAD

**Issue by limichange** [cocos/cocos-engine#2607]
http://forum.cocos.com/t/cc1-9-1-audiosource/59163/2

### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）
微信开发工具

### JavaScript output or error produced?（报错信息和调用栈）
https://github.com/cocos-creator/engine/blob/1ae826d8636d46e4c2356c07eb4ee6aecb996d50/cocos2d/audio/CCAudio.js#L159-L163

```
VM4533:1 gameThirdScriptError
Cannot read property 'destroy' of null;at setTimeout callback function
TypeError: Cannot read property 'destroy' of null
    at Audio.23.proto.destroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:5530:22)
    at CCClass.onDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:12654:20)
    at CCClass.destroyComp (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:21340:67)
    at CCClass._onPreDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:13284:36)
    at CCClass.133.prototype._destroyImmediate (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:23222:34)
    at CCClass._onPreDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:30431:21)
    at CCClass._onPreDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:8538:36)
    at CCClass.133.prototype._destroyImmediate (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:23222:34)
    at CCClass._onPreDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:30428:70)
    at CCClass._onPreDestroy (http://127.0.0.1:63212/game/cocos2d-js.f3e6f.js:8538:36)
```

```
	23.proto.destroy	@	CCAudio.js:180
onDestroy	@	cocos2d-js.f3e6f.js (old):12654
destroyComp	@	cocos2d-js.f3e6f.js (old):21340
_onPreDestroy	@	cocos2d-js.f3e6f.js (old):13284
133.prototype._destroyImmediate	@	cocos2d-js.f3e6f.js (old):23222
_onPreDestroy	@	cocos2d-js.f3e6f.js (old):30431
_onPreDestroy	@	cocos2d-js.f3e6f.js (old):8538
133.prototype._destroyImmediate	@	cocos2d-js.f3e6f.js (old):23222
_onPreDestroy	@	cocos2d-js.f3e6f.js (old):30428
_onPreDestroy	@	cocos2d-js.f3e6f.js (old):8538
133.prototype._destroyImmediate	@	cocos2d-js.f3e6f.js (old):23222
deferredDestroy	@	cocos2d-js.f3e6f.js (old):23133
runSceneImmediate	@	cocos2d-js.f3e6f.js (old):6731
(anonymous)	@	CCDirector.js:832
(anonymous)	@	CCAssetLibrary.js:110
(anonymous)	@	CCLoader.js:255
(anonymous)	@	utils.js:85
(anonymous)	@	WAGame.js:3
(anonymous)	@	WAGame.js:13
ontimeout	@	timers.js:469
tryOnTimeout	@	timers.js:304
listOnTimeout	@	timers.js:264
```

**Comment by jareguo** [comment]
fixed in https://github.com/cocos-creator/engine/pull/2596/files
