### ISSUE TITLE
微信开发者工具中报错

### ISSUE THREAD

**Issue by limichange** [cocos/cocos-engine#2610]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）
微信开发工具

### How to reproduce?（如何重现）
在微信开发工具里运行一段时间后 执行loadScene。web平台没有问题。

### JavaScript output or error produced?（报错信息和调用栈）
```js
      setContentSize: function(width, height) {
        if (void 0 === height) {
          height = width.height;
          width = width.width;
        }
        if (width === this._contentSize.width && height === this._contentSize.height) return;
        _ccsg.Node.prototype.setContentSize.call(this, width, height);
        this._quadsDirty = true;
      },
      ena
```

```

setContentSize | @ | CCScale9Sprite.js:1248
-- | -- | --
  | onResourceDataLoaded | @ | CCScale9Sprite.js:1198
  | setSpriteFrame | @ | CCScale9Sprite.js:1204
  | _onTextureLoaded | @ | CCSprite.js:540
  | _applySpriteFrame | @ | CCSprite.js:559
  | _initSgNode | @ | CCSprite.js:584
  | __preload | @ | CCRendererUnderSG.js:60
  | callPreload | @ | node-activator.js:46
  | (anonymous) | @ | component-scheduler.js:233
  | invoke | @ | node-activator.js:65
  | activateNode | @ | node-activator.js:225
  | _activate | @ | CCScene.js:96
  | runSceneImmediate | @ | CCDirector.js:615
  | (anonymous) | @ | CCDirector.js:832
  | (anonymous) | @ | CCAssetLibrary.js:110
  | (anonymous) | @ | CCLoader.js:255
  | (anonymous) | @ | utils.js:85
  | (anonymous) | @ | WAGame.js:3
  | (anonymous) | @ | WAGame.js:13
  | ontimeout | @ | timers.js:469
  | tryOnTimeout | @ | timers.js:304
  | listOnTimeout | @ | timers.js:264


```

```
VM5490:1 gameThirdScriptError
Cannot read property 'height' of null;at setTimeout callback function
TypeError: Cannot read property 'height' of null
    at TheClass.setContentSize (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:28434:25)
    at onResourceDataLoaded (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:28412:74)
    at TheClass.setSpriteFrame (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:28416:41)
    at CCClass._onTextureLoaded (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:14182:16)
    at CCClass._applySpriteFrame (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:14192:49)
    at CCClass._initSgNode (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:14205:14)
    at CCClass.__preload (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:13910:14)
    at callPreload (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:21189:9)
    at CCClass._invoke (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:12190:11)
    at CCClass.invoke (http://127.0.0.1:51760/game/cocos2d-js.0a3aa.js:21207:14)
console.error @ VM5490:1
errorReport @ WAGame.js:3
thirdErrorReport @ WAGame.js:3
(anonymous) @ WAGame.js:3
(anonymous) @ WAGame.js:13
ontimeout @ timers.js:469
tryOnTimeout @ timers.js:304
listOnTimeout @ timers.js:264
```

**Comment by jareguo** [comment]
谢谢反馈，已修复

**Comment by limichange** [comment]
@jareguo 辛苦辛苦
