### ISSUE TITLE
节点active设为false后，资源没有销毁

### ISSUE THREAD

**Issue by limichange** [cocos/cocos-engine#2625]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）

微信小游戏，web没有问题
### How to reproduce?（如何重现）
暂时没有办法重现

### JavaScript output or error produced?（报错信息和调用栈）

```
          uvs[5] = t;
          uvs[6] = r;
          uvs[7] = b;
        } else {
          l = (textureRect.x + texelCorrect) / atlasWidth;
          b = (textureRect.y + textureRect.height - texelCorrect) / atlasHeight;
          r = (textureRect.x + textureRect.width - texelCorrect) / atlasWidth;
          t = (textureRect.y + texelCorrect) / atlasHeight;
          uvs[0] = l;
          uvs[1] = b;
          uvs[2] = r;
          uvs[3] = b;
```
```
VM4711:1 gameThirdScriptError
Cannot read property 'x' of null
TypeError: Cannot read property 'x' of null
    at Object._calculateUVs (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:27697:27)
    at Object._rebuildQuads_base (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:27668:34)
    at TheClass._rebuildQuads (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:28593:42)
    at 164.cc.Scale9Sprite.WebGLRenderCmd.164.proto.updateTransform (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:28813:18)
    at 164.cc.Scale9Sprite.WebGLRenderCmd.transform (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:11008:14)
    at 164.cc.Scale9Sprite.WebGLRenderCmd._syncStatus (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:11179:52)
    at 164.cc.Scale9Sprite.WebGLRenderCmd.visit (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:11062:14)
    at TheClass.visit (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:10617:13)
    at CCClass.visit (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:10624:19)
    at CCClass.visit (http://127.0.0.1:63000/game/cocos2d-js.2673a.js:10627:43)
```

```
_calculateUVs | @ | CCScale9Sprite.js:197
-- | -- | --
  | _rebuildQuads_base | @ | CCScale9Sprite.js:164
  | _rebuildQuads | @ | CCScale9Sprite.js:1482
  | 164.proto.updateTransform | @ | CCScale9SpriteWebGLRenderCmd.js:89
  | transform | @ | CCSGNodeBaseRenderCmd.js:283
  | _syncStatus | @ | CCSGNodeBaseRenderCmd.js:560
  | visit | @ | CCSGNodeBaseRenderCmd.js:399
  | visit | @ | CCSGNode.js:1866
  | visit | @ | CCSGNode.js:1877
  | visit | @ | CCSGNode.js:1886
  | visit | @ | CCSGNode.js:1886
  | visit | @ | CCSGNode.js:1886
  | _visitScene | @ | CCDirector.js:304
  | mainLoop | @ | CCDirector.js:1491
  | callback | @ | CCGame.js:581
  | requestAnimationFrame (async) |   |  
  | wxRequestAnimationFrame | @ | gamePage.html:31
  | callback | @ | CCGame.js:575
  | requestAnimationFrame (async) |   |  
  | wxRequestAnimationFrame | @ | gamePage.html:31
  | callback | @ | CCGame.js:575
  | requestAnimationFrame (async) |   |  
  | wxRequestAnimationFrame | @ | gamePage.html:31
  | callback | @ | CCGame.js:575


```
### Demo project?（demo 项目）

暂时没有复现

**Comment by limichange** [comment]
不知道是不是和这个有关 https://github.com/cocos-creator/engine/pull/2611/。

做了这个修改后，就会报这个issue的错误
```
            if (!self.isValid) {
              return;
            }
```

**Comment by limichange** [comment]
原因找到了

https://github.com/cocos-laboratory/engine/commit/28665f39e0ccbc839160a5ee3b720674426c10c0

**Comment by limichange** [comment]
所有default_sprite_splash的节点都会有这个问题。

**Comment by jareguo** [comment]
抱歉没看出原因所在。能提供一个 demo 吗？
从你的修复来看，应该是 spriteFrame._rect 为空引起的。spriteFrame._rect 什么情况下会为空呢？
麻烦 @ColinCollins 跟进下这个问题

**Comment by ColinCollins** [comment]
收到。。。。

**Comment by limichange** [comment]
我直接用单色组件就会有这个问题。
![image](https://user-images.githubusercontent.com/1947344/39561260-30751788-4ed7-11e8-85e5-2cfe1326f6c1.png)
![image](https://user-images.githubusercontent.com/1947344/39561266-36af2bde-4ed7-11e8-90e7-33a6f48e7364.png)

我现在把默认的图片换成自己的了，之后就没有这个问题了。

**Comment by ColinCollins** [comment]
@limichange  我使用了 splash 默认图片 微信平台和Android 都没有出现报错啊，能否提供一下你的报错demo呢
引擎1.9.1
Android: 系统版本6.0.1
平台 1.02

**Comment by limichange** [comment]
我试着写一个demo试试。但我觉得那段代码还是需要check一下变量的。

**Comment by ColinCollins** [comment]
请问您的 demo 写出来了嘛？

**Comment by limichange** [comment]
目前复现不出来

**Comment by jareguo** [comment]
抱歉为了便于管理，我们会先关闭这个 issue。如果之后有其它信息，欢迎继续反馈！
