### ISSUE TITLE
v2.0.0-release Label组件使用.fnt字体文件编辑器中报错，但运行时没问题

### ISSUE THREAD

**Issue by hymanbuer** [cocos/cocos-engine#3073]
### Creator version?（版本号）
v2.0.0-release

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
随意新建一个Label节点，拖拽要使用的.fnt文件到Font字段。这在升级之前（v1.9.1）是没有问题的。

### JavaScript output or error produced?（报错信息和调用栈）

拖拽完成后报错：
TypeError: Cannot read property '_renderData' of null
    at Object.updateRenderData (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\renderer\utils\label\bmfont.js:122:22)
    at cc_Label._updateRenderData (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\components\CCLabel.js:366:37)
    at cc_Label.set (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\components\CCLabel.js:187:30)
    at cc_Label.n.set [as font] (F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\lib\asset-watcher.js:1:782)
    at F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\set-property-by-path.js:1:612
    at CCLoader.<anonymous> (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\platform\CCAssetLibrary.js:63:25)
    at F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\load-pipeline\CCLoader.js:134:46
    at F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\platform\utils.js:48:25
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

修改字体大小等属性警告：
Failed to set property label<Label> to 24 at fontSize, TypeError: Cannot read property '_renderData' of null
    at Object.updateRenderData (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\renderer\utils\label\bmfont.js:122:22)
    at cc_Label._updateRenderData (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\components\CCLabel.js:366:37)
    at cc_Label.set [as fontSize] (F:\DevTools\CocosCreator\resources\engine\bin\.cache\dev\cocos2d\core\components\CCLabel.js:104:30)
    at u (F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\set-property-by-path.js:1:2055)
    at y (F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\set-property-by-path.js:1:3802)
    at Object.b [as setPropertyByPath] (F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\set-property-by-path.js:1:4969)
    at Object.setProperty (F:\DevTools\CocosCreator\resources\app.asar\editor\page\scene-utils\utils\scene.js:1:8104)
    at HTMLElement.set-property (F:\DevTools\CocosCreator\resources\app.asar\editor\builtin\scene\panel\messages\scene-operation.js:1:778)
    at Object.e._dispatch (F:\DevTools\CocosCreator\resources\app.asar\editor-framework\lib\renderer\panel.js:1:1941)
    at EventEmitter.o.on.s (F:\DevTools\CocosCreator\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:2917)

### Demo project?（demo 项目）

无。

**Comment by Marssssssss** [comment]
您好，谢谢反馈。请问在目前版本还有这个问题吗？

**Comment by zhefengzhang** [comment]
在 2.4.4 测试，并没有复现问题。
