### ISSUE TITLE
微信小游戏子域项目里无法使用字体

### ISSUE THREAD

**Issue by MechaGirls** [cocos/cocos-engine#3883]
### Creator version?（版本号）
Cocos Creator v2.0.6

### Affected platform?（受影响的平台）

微信小游戏,当前开发平台mac os
### How to reproduce?（如何重现）
在子域项目里引入字体文件到Label上
![1550671777528](https://user-images.githubusercontent.com/21666293/53097477-7c4a0580-355c-11e9-86f1-31cadc013178.jpg)

### JavaScript output or error produced?（报错信息和调用栈）

<img width="667" alt="qq20190220-221347 2x" src="https://user-images.githubusercontent.com/21666293/53097612-d8ad2500-355c-11e9-97ca-0dad542773a7.png">

> VM9681:1 gameSubContextThirdScriptError
wx.loadFont is not a function;at setTimeout callback function
TypeError: wx.loadFont is not a function
    at m.loadFont (http://127.0.0.1:17477/game/NewProject_4/libs/engine/downloader.js:21:25)
    at m.107.m.handle (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:332908)
    at s (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:340800)
    at s (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:341064)
    at http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:340914
    at nextPipe (http://127.0.0.1:17477/game/NewProject_4/libs/wx-downloader.js:185:5)
    at window.WXDownloader.WXDownloader.handle (http://127.0.0.1:17477/game/NewProject_4/libs/wx-downloader.js:76:13)
    at s (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:340800)
    at s (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:341064)
    at s (http://127.0.0.1:17477/game/NewProject_4/cocos2d-js-min.bdea5.js:1:341064)

### Demo project?（demo 项目）

https://github.com/2015-lizaiyang/wx-open-data-project

**Comment by zhefengzhang** [comment]
你好，这是微信小游戏对开发数据域的限制。微信小游戏开发数据域只能支持加载图片。参考：https://developers.weixin.qq.com/minigame/dev/guide/open-ability/open-data.html
