### ISSUE TITLE
新建Vivo小游戏编译运行就报错

### ISSUE THREAD

**Issue by fuyifan** [cocos/cocos-engine#4263]
### Creator version?（版本号）
2.0.7 2.0.9

### Affected platform?（受影响的平台）

vivo 小游戏

### How to reproduce?（如何重现）
新建项目就会出问题

### JavaScript output or error produced?（报错信息和调用栈）
java.lang.RuntimeException: (see stack)Uncaught TypeError: Cannot read property 'createBuffer' of undefined[0]VertexBuffer@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:30429
[1]ctor@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:37972
[2]superCallBounded.super@/data/user/0/com.vivo.hybrid/appresource/com.zstar.bricking/src/cocos2d-runtime.js:21794
[3]getBuffer@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:38236
[4]RenderComponentWalker@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:38129
[5]initWebGL@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:26665
[6]initRenderer@/data/user/0/com.vivo.hybrid/appresource/com.zstar.bricking/src/cocos2d-runtime.js:5939
[7]initEngine@/data/user/0/com.vivo.hybrid/appresource/com.zstar.bricking/src/cocos2d-runtime.js:5742
[8]prepareFinished@/data/user/0/com.vivo.hybrid/appresource/com.zstar.bricking/src/cocos2d-runtime.js:5750
[9]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:5775
[10]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:19242
[11]anonymous@/data/user/0/com.vivo.hybrid/app_resource/com.zstar.bricking/src/cocos2d-runtime.js:25805
[12]anonymous@@assets/default/_jsb-builtin.js:1
[13]A@@assets/default/_jsb-builtin.js:1
at com.vivo.hybrid.game.jsruntime.GameRuntime$3.run(SourceFile:280)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7425)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by fuyifan** [comment]
升级快应用就好了
