### ISSUE TITLE
[2.1.1] Android build failed if python3 is a default python interpreter.

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#4608]
### Issue

Android build works if python2 is a default python interpreter, but it doesn't if python3 is a default python interpreter.
Cocos Creator 2.0.9 works even if python3 is a default python interpreter.

### Expected behavior
Android build should work regardless of the python version of the user's machine. Cocos creator should use the embedded python runtime.

### Creator version?（版本号）
2.1.1, 2.1.2 (2.0.9 doesn't have this issue)

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）

1. install python3 on mac
   brew install python
1. make a symbolic link of python3
   unlink /usr/local/bin/python
   ln -s /usr/local/bin/python3 /usr/local/bin/python
1. confirm python version
   python -V
1. Build an empty project for android. (make sure the build directory is clean)
   

### JavaScript output or error produced?（报错信息和调用栈）
2019-06-12T22:30:29.803Z - normal: Load ~/.CocosCreator/settings.json
2019-06-12T22:30:29.848Z - normal: Initializing Asset Database
2019-06-12T22:30:29.850Z - normal: checking language setting...
2019-06-12T22:30:29.851Z - normal: Language: en
2019-06-12T22:30:30.346Z - success: preview server running at http://localhost:7456
2019-06-12T22:30:30.375Z - success: protocol editor-framework registered
2019-06-12T22:30:30.375Z - success: protocol app registered
2019-06-12T22:30:30.376Z - success: protocol theme registered
2019-06-12T22:30:30.376Z - success: protocol packages registered
2019-06-12T22:30:30.376Z - success: protocol uuid registerred
2019-06-12T22:30:30.376Z - success: protocol db registerred
2019-06-12T22:30:30.376Z - success: protocol thumbnail registerred
2019-06-12T22:30:30.376Z - success: protocol unpack registerred
2019-06-12T22:30:30.376Z - success: protocol disable-commonjs registerred
2019-06-12T22:30:31.128Z - normal: connected!
2019-06-12T22:30:31.129Z - normal: Check project /Users/hyuhoonkwon/Documents/cocos2/cocos211
2019-06-12T22:30:31.130Z - normal: Initializing project /Users/hyuhoonkwon/Documents/cocos2/cocos211
2019-06-12T22:30:31.405Z - normal: Initializing Cocos2d
2019-06-12T22:30:32.059Z - normal: Initializing engine extends
2019-06-12T22:30:32.099Z - success: asset-db-debugger loaded
2019-06-12T22:30:32.100Z - success: baidu-adapter loaded
2019-06-12T22:30:32.101Z - success: color-picker loaded
2019-06-12T22:30:32.165Z - success: fb-audience-network loaded
2019-06-12T22:30:32.196Z - success: fb-live-stream loaded
2019-06-12T22:30:32.200Z - success: google-play-instant loaded
2019-06-12T22:30:32.204Z - success: huawei-runtime loaded
2019-06-12T22:30:32.205Z - success: jsb-adapter loaded
2019-06-12T22:30:32.209Z - success: oppo-runtime loaded
2019-06-12T22:30:32.224Z - success: package-manager loaded
2019-06-12T22:30:32.311Z - success: qqplay-adapter loaded
2019-06-12T22:30:32.314Z - success: runtime-dev-tools loaded
2019-06-12T22:30:32.391Z - success: sdkbox loaded
2019-06-12T22:30:32.407Z - success: tester loaded
2019-06-12T22:30:32.424Z - success: ui-grid loaded
2019-06-12T22:30:32.439Z - success: ui-kit-preview-extra loaded
2019-06-12T22:30:32.455Z - success: ui-kit-preview loaded
2019-06-12T22:30:32.470Z - success: ui-kit loaded
2019-06-12T22:30:32.485Z - success: ui-tree loaded
2019-06-12T22:30:32.489Z - success: vivo-runtime loaded
2019-06-12T22:30:32.490Z - success: weapp-adapter loaded
2019-06-12T22:30:32.536Z - success: assets loaded
2019-06-12T22:30:32.551Z - success: builder loaded
2019-06-12T22:30:32.755Z - success: cocos-services loaded
2019-06-12T22:30:32.771Z - success: console loaded
2019-06-12T22:30:32.800Z - success: fb-instant-games loaded
2019-06-12T22:30:32.815Z - success: game-window loaded
2019-06-12T22:30:32.817Z - success: google-instant-games loaded
2019-06-12T22:30:32.832Z - success: hierarchy loaded
2019-06-12T22:30:32.847Z - success: inspector loaded
2019-06-12T22:30:32.849Z - success: keystore loaded
2019-06-12T22:30:32.863Z - success: node-library loaded
2019-06-12T22:30:32.865Z - success: package-asset loaded
2019-06-12T22:30:32.865Z - success: preferences loaded
2019-06-12T22:30:32.881Z - success: project-exporter loaded
2019-06-12T22:30:32.898Z - success: project-importer loaded
2019-06-12T22:30:32.912Z - success: project-settings loaded
2019-06-12T22:30:32.929Z - success: scene loaded
2019-06-12T22:30:32.931Z - success: simulator-debugger loaded
2019-06-12T22:30:32.932Z - success: sprite-editor loaded
2019-06-12T22:30:32.947Z - success: store loaded
2019-06-12T22:30:32.963Z - success: timeline loaded
2019-06-12T22:30:33.758Z - normal: Loading packages
2019-06-12T22:30:33.762Z - normal: Watching packages
2019-06-12T22:30:33.830Z - normal: Run Application
2019-06-12T22:30:36.612Z - info: Cocos Services load base data!
2019-06-12T22:30:44.618Z - normal: Start building with options : {
  "actualPlatform": "android",
  "android-instant": {
    "REMOTE_SERVER_ROOT": "",
    "host": "",
    "pathPattern": "",
    "recordPath": "",
    "scheme": "https",
    "skipRecord": false
  },
  "apiLevel": "android-28",
  "appABIs": [],
  "appBundle": false,
  "baidugame": {
    "REMOTE_SERVER_ROOT": "",
    "appid": "testappid",
    "orientation": "portrait",
    "subContext": ""
  },
  "buildPath": "/Users/hyuhoonkwon/Documents/cocos2/cocos211/build",
  "debug": false,
  "dest": "/Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link",
  "embedWebDebugger": false,
  "encryptJs": true,
  "excludeScenes": [],
  "excludedModules": [],
  "fb-instant-games": {},
  "includeSDKBox": false,
  "inlineSpriteFrames": true,
  "inlineSpriteFrames_native": true,
  "md5Cache": false,
  "mergeStartScene": false,
  "optimizeHotUpdate": false,
  "orientation": {
    "landscapeLeft": true,
    "landscapeRight": true,
    "portrait": false,
    "upsideDown": false
  },
  "packageName": "org.cocos2d.cocos211",
  "platform": "android",
  "previewHeight": "720",
  "previewWidth": "1280",
  "qqplay": {
    "REMOTE_SERVER_ROOT": "",
    "orientation": "portrait",
    "zip": false
  },
  "scenes": [
    "2e415ed7-6129-4021-99be-877c2cc70c38"
  ],
  "sourceMaps": false,
  "startScene": "2e415ed7-6129-4021-99be-877c2cc70c38",
  "template": "link",
  "title": "cocos211",
  "useDebugKeystore": true,
  "vsVersion": "auto",
  "webOrientation": "auto",
  "wechatgame": {
    "REMOTE_SERVER_ROOT": "",
    "appid": "wx6ac3f5090a6b99c5",
    "orientation": "portrait",
    "subContext": ""
  },
  "xxteaKey": "1fe71224-3b72-4d",
  "zipCompressJs": true,
  "project": "/Users/hyuhoonkwon/Documents/cocos2/cocos211",
  "projectName": "cocos211",
  "debugBuildWorker": false
}
2019-06-12T22:30:44.621Z - normal: Building /Users/hyuhoonkwon/Documents/cocos2/cocos211
2019-06-12T22:30:44.621Z - normal: Destination /Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link
2019-06-12T22:30:44.714Z - normal: Delete /Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link/subpackages/**/*,/Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link/res/**/*,/Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link/src/**/*
2019-06-12T22:30:44.823Z - failed: Traceback (most recent call last):
  File "/Applications/CocosCreator211.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 1012, in <module>
    if not _check_python_version():
  File "/Applications/CocosCreator211.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 943, in _check_python_version
    print(MultiLanguage.get_string('COCOS_PYTHON_VERSION_TIP_FMT') % (major_ver, minor_ver))
  File "/Applications/CocosCreator211.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/MultiLanguage.py", line 52, in get_string
    fmt = cls.get_instance().get_current_string(key)
  File "/Applications/CocosCreator211.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/MultiLanguage.py", line 46, in get_instance
    cls.instance = MultiLanguage()
  File "/Applications/CocosCreator211.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/MultiLanguage.py", line 97, in __init__
    self.cfg_info = json.load(f, encoding='utf-8')
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/bin/../Cellar/python/3.6.4_3/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 30196: ordinal not in range(128)

2019-06-12T22:30:44.831Z - normal: Creating native cocos project to  /Users/hyuhoonkwon/Documents/cocos2/cocos211/build/jsb-link
2019-06-12T22:30:44.939Z - error: Build Failed: Error: Failed to create project with exitCode : 1
    at ChildProcess.c.error.q (/Applications/CocosCreator211.app/Contents/Resources/app.asar/editor/core/native-utils.js:1:14625)
    at ChildProcess.r.on (/Applications/CocosCreator211.app/Contents/Resources/app.asar/editor/core/native-utils.js:1:6589)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
    at r.waterfall.r (/Applications/CocosCreator211.app/Contents/Resources/app.asar/editor/lib/builder/index.js:1:3393)
    at /Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at /Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:696:30
    at /Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:167:37
    at /Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:1209:30
    at Gulp.doneCallback (/Applications/CocosCreator211.app/Contents/Resources/app.asar/editor/core/gulp-build.js:1:28089)
    at Gulp.Orchestrator.stop (/Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/orchestrator/index.js:150:9)
    at /Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/orchestrator/index.js:277:22
    at finish (/Applications/CocosCreator211.app/Contents/Resources/app.asar/node_modules/orchestrator/lib/runTask.js:21:8)

### Demo project?（demo 项目）

Create an empty project.

**Comment by jareguo** [comment]
Maybe we should embed a standalone python 2.7 in the editor, just as Windows.
@wuzhiming Search "Python27" in the editor, make them take effect on Mac please.

**Comment by Parahexen** [comment]
One more year and still not fixed in 2.4.2.

**Comment by wuzhiming** [comment]
CocosCreator 3.0 version will remove python script and use js script to build project instead. See https://github.com/cocos-creator/cocos2d-x-lite/pull/2670

**Comment by thienhaflash** [comment]
> One more year and still not fixed in 2.4.2.

A temporary workaround (especially for Catalina) is opening the **cocos** build script and change from **python** to **python2**

Open the **cocos** file located in `/Applications/CocosCreator/Creator/2.4.6/CocosCreator.app/Contents/Resources/cocos2d-x/tools/cocos2d-console/bin/cocos` with your text editor (maybe VSCode), and change the last line

from:
`python "$COCOS_CONSOLE_BIN_DIRECTORY/cocos.py" "$@"`

to:
`python2 "$COCOS_CONSOLE_BIN_DIRECTORY/cocos.py" "$@"`

Hope it works for you!
