### ISSUE TITLE
shader 问题

### ISSUE THREAD

**Issue by zero16832** [cocos/cocos-engine#4911]
2.0.9 的shader 在 升级到 2.1.12之后 报错

提示信息如下：
load script [spriteShader] failed : TypeError: Cannot read property 'length' of undefined
    at ProgramLib.define (C:\CocosCreator_2.1.2\resources\engine\bin\.cache\dev\cocos2d\renderer\core\program-lib.js:129:52)
    at temp\quick-scripts\assets\scripts\shader\spriteShader.js:16:38
    at Object.once (C:\CocosCreator_2.1.2\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:146:30)
    at __define (temp\quick-scripts\assets\scripts\shader\spriteShader.js:15:9)
    at temp\quick-scripts\assets\scripts\shader\spriteShader.js:24:13
    at Object.<anonymous> (temp\quick-scripts\assets\scripts\shader\spriteShader.js:31:11)
    at Object.<anonymous> (temp\quick-scripts\assets\scripts\shader\spriteShader.js:34:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
 
The base class to extend from must be non-nil
    at Object.cc.errorID (C:\CocosCreator_2.1.2\resources\engine\bin\.cache\dev\cocos2d\core\CCDebug.js:167:16)
    at Object.extend (C:\CocosCreator_2.1.2\resources\engine\bin\.cache\dev\cocos2d\core\platform\js.js:81:28)
    at __define (temp\quick-scripts\assets\scripts\shader\spriteMaterial.js:34:7)
    at temp\quick-scripts\assets\scripts\shader\spriteMaterial.js:115:13
    at Object.<anonymous> (temp\quick-scripts\assets\scripts\shader\spriteMaterial.js:122:11)
    at Object.<anonymous> (temp\quick-scripts\assets\scripts\shader\spriteMaterial.js:125:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by yeshao2069** [comment]
你好，这个问题方便提供Demo这边排查？

如果没办法提供Demo, 推荐你 升级至  2.4.x最新的版本 2.4.5，并重试。
https://docs.cocos.com/creator/manual/zh/render/effect.html?h=shader
https://docs.cocos.com/creator3d/manual/zh/material-system/overview.html

**Comment by zhefengzhang** [comment]
客户长时间未回复，暂时关闭。
