### ISSUE TITLE
資源引用了package提供的組件會無法導出

### ISSUE THREAD

**Issue by meifujiwara** [cocos/cocos-engine#5156]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）

編輯器

### How to reproduce?（如何重现）
場景或prefab若引用了package提供的組件，拉到導出資源面板上時會報錯並呈現一直Loading的狀態

![圖片](https://user-images.githubusercontent.com/24955257/63006430-1e65fd00-beb1-11e9-89b5-e85fa0f8c540.png)

### JavaScript output or error produced?（报错信息和调用栈）

Error: ENOENT: no such file or directory, stat 'C:\NewProject\assets\el-node'
    at fs.statSync (fs.js:973:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:298:16)
    at Object.statSync (C:\CocosCreator\resources\app.asar\node_modules\graceful-fs\polyfills.js:295:24)
    at d (C:\CocosCreator\resources\app.asar\editor\builtin\package-asset\parse\export.js:1:803)
    at C:\CocosCreator\resources\app.asar\editor\builtin\package-asset\parse\export.js:1:1452
    at Editor.assetdb.queryInfoByUuid (C:\CocosCreator\resources\app.asar\editor\builtin\package-asset\parse\export.js:1:1501)
    at EventEmitter.o.on.n (C:\CocosCreator\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:3753)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)

**Comment by yeshao2069** [comment]
你好，这个方便提供一个demo？

**Comment by yeshao2069** [comment]
感谢反馈，使用2.4.6测试，问题仍然存在，已经提交给引擎组排查。
