### ISSUE TITLE
cc.Vec3 无法序列化

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5276]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）
Mac Editor

####  stpe 1
创建一个测试脚本文件： TestVec3.ts
#### step 2
写入以下内容：
``` Typescript
const {ccclass, property} = cc._decorator;

@ccclass
export default class TestVec3 extends cc.Component{
    /** test value */
    @property({tooltip : "test value"})
    public test : cc.Vec3 = new cc.Vec3(0, 0, 0);
    
}
````
#### step 3 
保存这个脚本文件，并新建一个node，将文件挂载上去。。就会发现，不能将这个组件脚本挂载到新建的node上面

### JavaScript output or error produced?（报错信息和调用栈）
```
TypeError: Cannot read property 'x' of undefined
    at e (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/inspector/utils/utils.js:1:1621)
    at t (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/inspector/utils/utils.js:1:1906)
    at Object.buildNode (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/inspector/utils/utils.js:1:2318)
    at HTMLElement._handleQueryNode (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/inspector/panel/index.js:1:11052)
    at t.map (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/inspector/panel/index.js:1:10897)
    at /Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at /Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:361:13
    at /Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at done (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:246:17)
    at /Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:44:16
```

**Comment by SantyWang** [comment]
感谢反馈，之后版本已修复
