### ISSUE TITLE
某些正则表达式导致脚本失效

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#5328]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）

Web
### How to reproduce?（如何重现）
`new RegExp(/(([^,"]+)|("[^"]*")|((?<=,|^)\s*))(?=,|$)/g)`
在任意项目中写入一个上面的正则表达式，则会导致此脚本解析失败，关闭项目后打开时报错。
并非所有正则都会导致此问题，我在项目中用到的另外一个正则`/.+(?=\r\n)/g`并不会导致此bug。

### JavaScript output or error produced?（报错信息和调用栈）

（以标准的heollo-typescript项目为例，在Helloworld.ts中写入以上正则）
在web中的报错信息为：
```
CCDebug.js:249 Can not find class 'e1b90/rohdEk4SdmmEZANaD'（CCDebug.js:249 ）
Script attached to 'Canvas' is missing or invalid.（CCDebug.js:249）
```
重新打开项目报错信息为：
```
Error parsing regular expression: Invalid regular expression: /(([^,"]+)|("[^"]*")|((?<=,|^)\s*))(?=,|$)/: Invalid group (34:28) while parsing /Users/fengyong/Documents/workspace/empty-cocos-project/temp/quick-scripts/assets/Script/Helloworld.js while parsing file: /Users/fengyong/Documents/workspace/empty-cocos-project/temp/quick-scripts/assets/Script/Helloworld.js

SyntaxError: Error parsing regular expression: Invalid regular expression: /(([^,"]+)|("[^"]*")|((?<=,|^)\s*))(?=,|$)/: Invalid group (34:28) while parsing /Users/fengyong/Documents/workspace/empty-cocos-project/temp/quick-scripts/assets/Script/Helloworld.js while parsing file: /Users/fengyong/Documents/workspace/empty-cocos-project/temp/quick-scripts/assets/Script/Helloworld.js
    at DestroyableTransform.end [as _flush] (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.prefinish (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)
    at prefinish (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:293:19)
```

**Comment by Marssssssss** [comment]
你好，我这里最新版本 creator 没有重现这个问题，请使用最新版本的 creator 再试试看看。

**Comment by fkworld** [comment]
我在 2.1.3 版本中依然复现了这个问题

**Comment by Marssssssss** [comment]
可以提供一份 demo 吗？我这里可能复现的方式有误。

**Comment by fkworld** [comment]
demo 就是标准的 hello-typescript 项目，只需要在 Helloworld.ts 文件中增加一行代码就会复现。

> 我这里可能复现的方式有误。

你的复现方式是什么样的呢？有其他人复现成功或失败吗？

**Comment by Marssssssss** [comment]
按照您说的复现方式我这里 2.2.0-rc5 版本没有出现报错，重开项目也是正常的。
应该是在 2.2.0 已经被修复了。

**Comment by fkworld** [comment]
我只在 2.0.10 和 2.1.3 中复现过，并没有使用 2.2.0 版本。
我看到一个类似的问题，不知是否是 cocos 出现问题的原因。
https://stackoverflow.com/questions/5952936/invalid-regular-expression-error

**Comment by Marssssssss** [comment]
我这里 2.1.2 按这个方法确实出现问题了。2.2.0 就没有这个问题，应该已经修复了。

**Comment by Marssssssss** [comment]
> 我只在 2.0.10 和 2.1.3 中复现过，并没有使用 2.2.0 版本。
> 我看到一个类似的问题，不知是否是 cocos 出现问题的原因。
> https://stackoverflow.com/questions/5952936/invalid-regular-expression-error

这个问题看下面的回答是因为在不适配 ECMAScript 2018 的 JS 环境下不支持某个符号导致的。
