### ISSUE TITLE
getComponent: Type must be non-nil

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5380]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）
未知

### JavaScript output or error produced?（报错信息和调用栈）
getComponent: Type must be non-nil
    at Object.cc.errorID (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/CCDebug.js:167:16)
    at getConstructor (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/utils/base-node.js:29:20)
    at cc_Node.getComponent (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/utils/base-node.js:399:35)
    at HTMLElement.query-node-info (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor/builtin/scene/panel/messages/scene-query.js:1:1331)
    at Object.e._dispatch (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor-framework/lib/renderer/panel.js:1:1941)
    at EventEmitter.o.on.s (/Applications/Cocos/CocosCreator_2.0.10.app/Contents/Resources/app.asar/editor-framework/lib/renderer/ipc.js:1:2921)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)

**Comment by balazsnemeth** [comment]
I'm getting the same error, any news on this? How can we track it down which component has the issue?

**Comment by fjqingyou** [comment]
Sorry, No progress

**Comment by SantyWang** [comment]
So sorry for late reply, could you please give us more information about how to reproduce this issue? Would it affect your operations in editor? Editor get stuck?

**Comment by fjqingyou** [comment]
@holycanvas 坐标深圳？我英文不行就不翻译啦。

不影响正常使用。但是经常性在编辑器中出现这个错误提示。重现方式暂且未知，不确定它是如何触发的问题。

**Comment by yeshao2069** [comment]
感谢反馈，建议升级到目前最新的版本(2.4.5或者3.1.0)。
如何查找是哪个组件出现的问题，你可以尝试在getComponent函数断点查看，在哪里使用这个函数的时候导致的问题。
如果有可以复现的方式，欢迎告知我们，我们会即使排查并解决，谢谢！

Thanks for the feedback, it is recommended to upgrade to the latest version available (2.4.5 or 3.1.0).
How to find out which component is causing the problem, you can try to see at the getComponent function breakpoint where the use of this function is causing the problem.
If there is a way to reproduce it, please let us know and we will troubleshoot and fix it , thanks!
