### ISSUE TITLE
加载器跟 Node.js 的 `require` 不一致

### ISSUE THREAD

**Issue by arniu** [cocos/cocos-engine#6356]
# Creator version?（版本号）

v2.3.1

### Affected platform?（受影响的平台）

仅使用 Mac Editor，其他情况不明。

### How to reproduce?（如何重现）

搭建 monorepo 项目，目录结构如下：

```
root
├── app
│   ├── assets
│   ├── node_modules
│   └── package.json // <1>
├── node_modules/
├── package.json      // <0>
├── server
│   ├── node_modules
│   └── package.json // <2>
└── yarn.lock
```

共有三个 `package.json` 文件，对应三个模块：

- <0> root: 根，开启 [`workspace`][yarn-workspace]，用于管理其他模块；
- <1> app: cocos 游戏，依赖第三方模块，比如 `uuid`；
- <2> server: 与此问题无关，不表。

开启 `workspace` 后，`app` 的模块安装在 `root` 目录下的 `node_modules` 中，自己的 `node_modules` 基本清空。Node.js 的[机制][node-module]是递归的向上查找，`require` 是没有问题的。

[node-module]: https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_loading_from_node_modules_folders
[yarn-workspace]: https://yarnpkg.com/features/workspaces

### JavaScript output or error produced?（报错信息和调用栈）

```
load script [uuid] failed : Error: Cannot find module 'uuid'
Require stack:
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/project-scripts.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/scene-utils/lib/sandbox.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/scene-utils/edit-mode/index.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/scene-utils/index.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/editor.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/index.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor-framework/renderer.js
- /Applications/CocosCreator.app/Contents/Resources/app.asar/editor/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Function.Module._resolveFilename [as _resolveFilenameVendor] (/Applications/CocosCreator.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.u._resolveFilename (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/project-scripts.js:1:1330)
    at Function.Module._load (internal/modules/cjs/loader.js:601:27)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.cc.require (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/page/project-scripts.js:1:747)
    at __require (<path to cocos app>/temp/quick-scripts/dst/assets/<file using uuid>.js:7:35)
    at __define (<path to cocos app>/temp/quick-scripts/dst/assets/<file using uuid>.js:25:16)
    at <path to cocos app>/temp/quick-scripts/dst/assets/<file using uuid>.js:142:25
```

### Demo project?（demo 项目）

暂无。

**Comment by zhefengzhang** [comment]
这个问题可以参考这个帖子中的方案解决：
https://forum.cocos.org/t/topic/101523
