### ISSUE TITLE
[BUG] 2.3.3版本，项目中的tsconfig.json影响实际编译

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#6664]
creator版本：2.3.3

根据文档描述，应该是不影响的：

> 注意：项目中的 tsconfig.json 主要是用于配合 VS Code，并不会影响项目在 Creator 中的实际编译。
> http://docs.cocos.com/creator/manual/zh/scripting/typescript.html

在2.3.3中，会影响实际编译。
复现流程为：
1. 新建空的 hello-typescript 项目
2. 新建脚本`a.ts`，内容为`export const a = 1; cc.log(a);`，则会在编辑器中输出`1`。（正常）
3. 修改`tsconfig.json`，将`compilerOptions-module`改为`esnext`。
4. 在`a.ts`文件中新增行删除行，并保存。（如果文件没有改动则有编译缓存)
5. 点击编辑器中的`开发者-重新加载界面`，等待刷新后编辑器报错。

报错信息为：
```
load script [./assets/Script/a] failed : /Users/fengyong/Documents/workspace/NewProject/temp/quick-scripts/dst/assets/Script/a.js:16
export var a = 1;
^^^^^^
SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:766:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
