### ISSUE TITLE
本地模拟器跑socket.io 2.3.0出错

### ISSUE THREAD

**Issue by MikiraSora** [cocos/cocos-engine#6736]
### Creator version?（版本号）
2.3.2

### Affected platform?（受影响的平台）
Simulator 

### How to reproduce?（如何重现）
通过npm install 得到socket.io client 2.3.0,然后import使用时出现以下情况:
```
Simulator: E/jswrapper (682): ScriptEngine::evalString script E:/CatchJokerPoker/assets/script/lib/socketio/socket.io.js, failed!
Simulator: E/jswrapper (300): [ERROR] Failed to invoke require, location: f:\jenkins\workspace\creator_2d\cocos2d-x-lite\windows\cocos2d-x-lite\cocos\scripting\js-bindings\manual\jsb_global.cpp:300
Simulator: E/jswrapper (272): ERROR: Uncaught ReferenceError: self is not defined, location: E:/CatchJokerPoker/assets/script/lib/socketio/socket.io.js:0:0
```
![](https://puu.sh/FNrAg/7e26dad640.png)
浏览器模拟器正常

### JavaScript output or error produced?（报错信息和调用栈）
```
Simulator: E/jswrapper (682): ScriptEngine::evalString script E:/CatchJokerPoker/assets/script/lib/socketio/socket.io.js, failed!
    at HTMLElement.print-simulator-log (C:\CocosDashboard_1.0.6\resources\.editors\Creator\2.3.2\resources\app.asar\editor\builtin\scene\panel\messages\scene.js:1:1608)
    at Object.e._dispatch (C:\CocosDashboard_1.0.6\resources\.editors\Creator\2.3.2\resources\app.asar\editor-framework\lib\renderer\panel.js:1:1876)
    at EventEmitter.<anonymous> (C:\CocosDashboard_1.0.6\resources\.editors\Creator\2.3.2\resources\app.asar\editor-framework\lib\renderer\ipc.js:1:2952)
    at EventEmitter.emit (events.js:194:13)
    at EventEmitter.emit (domain.js:469:20)
    at EventEmitter.topLevelDomainCallback (domain.js:124:23)
```

### Demo project?（demo 项目）
莫得

### 我的解决方法
直接去socket.io.js文件添加对self的赋值:
![](https://puu.sh/FNrBC/f623834881.png)

**Comment by xianyinchen** [comment]
你可以安装client版本
npm install socket.io-client

然后提取里面的放到creator设置成插件
node_modules/socket.io-client/dist/socket.io.min.js

详见npm库和对应文档
https://www.npmjs.com/package/socket.io-client
https://socket.io/docs/v4/client-initialization/

**Comment by xianyinchen** [comment]
引擎对该npm库的兼容性存在问题，可以按照你的操作方法规避，或者使用下面这个帖子里面的socket.io库文件
https://forum.cocos.org/t/typescript-socket-io/51670/2
