### ISSUE TITLE
[模拟器] 简单写了个测试，web可以跑，模拟器报错

### ISSUE THREAD

**Issue by Ostding** [cocos/cocos-engine#6915]
版本：2.4
错误堆栈：
Simulator: ERROR: Uncaught TypeError: Cannot read property 'updateMeshData' of null, location: src/cocos2d-jsb.js:0:0
STACK:
[0]_updateMeshAttribute@src/cocos2d-jsb.js:38739
[1]_setMesh@src/cocos2d-jsb.js:38687
[2]set@src/cocos2d-jsb.js:38603
[3]PlanetGenerator.createPlanet@dst/assets/Script/generators/PlanetGenerator.js:58
[4]Helloworld.onBtnGenPlanet@dst/assets/Script/Helloworld.js:126
[5]emit@src/cocos2d-jsb.js:28889
[6]emitEvents@src/cocos2d-jsb.js:28872
[7]_onTouchEnded@src/cocos2d-jsb.js:28465
[8]285.proto.emit@src/cocos2d-jsb.js:44895
[9]_doDispatchEvent@src/cocos2d-jsb.js:18272
[10]dispatchEvent@src/cocos2d-jsb.js:19165
[11]_touchEndHandler@src/cocos2d-jsb.js:18160
[12]_onTouchEventCallback@src/cocos2d-jsb.js:35757
[13]_dispatchEventToListeners@src/cocos2d-jsb.js:35843
[14]_dispatchTouchEvent@src/cocos2d-jsb.js:35792
[15]dispatchEvent@src/cocos2d-jsb.js:36044
[16]handleTouchesEnd@src/cocos2d-jsb.js:42887
[17]_mouseEventsOnElement@src/cocos2d-jsb.js:43034
[18]anonymous@src/cocos2d-jsb.js:43053
[19]dispatchEvent@jsb-adapter/jsb-builtin.js:3069
[20]anonymous@jsb-adapter/jsb-builtin.js:3141
[ERROR] (/Users/nantas/jenkins/workspace/Creator_2D/cocos2d-x-lite/mac/cocos2d-x-lite/cocos/scripting/js-bindings/jswrapper/v8/Object.cpp, 574): Invoking function (0x7fef75a15af0) failed!
    at HTMLElement.print-simulator-log (/Applications/CocosCreator/Creator/2.4.0-rc.8/CocosCreator.app/Contents/Resources/app.asar/editor/builtin/scene/panel/messages/scene.js:1:1606)
    at Object.e._dispatch (/Applications/CocosCreator/Creator/2.4.0-rc.8/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/panel.js:1:1876)
    at EventEmitter.<anonymous> (/Applications/CocosCreator/Creator/2.4.0-rc.8/CocosCreator.app/Contents/Resources/app.asar/editor-framework/lib/renderer/ipc.js:1:2952)
    at EventEmitter.emit (events.js:194:13)
    at EventEmitter.emit (domain.js:469:20)
    at EventEmitter.topLevelDomainCallback (domain.js:124:23)
重现步骤：
   用模拟器运行测试工程，点击中间的测试按钮，就会出现上述错误，工程代码再浏览器中没有错误。
测试工程：
[test.zip](https://github.com/cocos-creator/engine/files/4810997/test.zip)

**Comment by hcb1135** [comment]
同遇到这个问题了

**Comment by AlbertMunto** [comment]
我也遇到相同的情況 確認過自己程式碼沒有錯誤

**Comment by eastcowboy2002** [comment]
ERROR: Uncaught TypeError: Cannot read property ‘updateMeshData’ of null

我也遇到这个问题，并且解决了。
做法是不要在创建 MeshRenderer 的那一帧内设置它的 .mesh 属性。而是延迟到下一帧。cocos 这些年，遇到的莫名 bug 大家都可以试试这招：延迟到下一帧。意外的可以解决很多问题。

**Comment by xianyinchen** [comment]
因为原生渲染器与与Web端的渲染器有所区别，你可以使用下面方法规避问题。

``` javascript
let renderer = node.addComponent(cc.MeshRenderer);  
renderer.__preload();
renderer.mesh = mesh;
```
