### ISSUE TITLE
creator 2.4.3 调试动画导致编辑器崩溃

### ISSUE THREAD

**Issue by darklinden** [cocos/cocos-engine#8288]
Creator 版本： 2.4.3 - 2.4.4

目标平台：

重现方式：
美术做动画时编辑器崩了，我让丢过来一个导出资源，打开没问题，调试动画，点取消编辑动画，确定，崩

首个报错：
TypeError: Cannot read property ‘_assembler’ of null
at RenderFlow._proto._updateRenderData (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:92:8)
at RenderFlow._proto._worldTransform (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:63:14)
at RenderFlow._proto._localTransform (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:47:14)
at RenderFlow._proto._children (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:130:26)
at RenderFlow._proto._worldTransform (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:63:14)
at RenderFlow._proto._localTransform (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:47:14)
at RenderFlow._proto._children (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:130:26)
at Function.RenderFlow.visitRootNode (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:270:33)
at Function.RenderFlow.render (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/render-flow.js:280:14)
at Object.render (/Applications/Cocos/2.4.4/CocosCreator.app/Contents/Resources/engine/bin/.cache/dev/cocos2d/core/renderer/index.js:209:18)

之前哪个版本是正常的：

手机型号：

手机浏览器：

编辑器操作系统：

重现概率： 必现
[Sample.zip](https://github.com/cocos-creator/engine/files/6035842/Sample.zip)

**Comment by darklinden** [comment]
经测试，当动画对含有cc.Mask控件的节点的cc.Node.active操作时，关闭动画会导致报错

**Comment by yeshao2069** [comment]
checking

**Comment by yeshao2069** [comment]
问题可以复现，已经反馈给引擎组排查。
