### ISSUE TITLE
2.4.5持续集成功能无效，任意工程，Cannot read property 'getParameter' of null

### ISSUE THREAD

**Issue by qx** [cocos/cocos-engine#8638]
### Creator version?（版本号）
2.4.5

### Affected platform?（受影响的平台）
Windows Editor 

### How to reproduce?（如何重现）
阿里云windows2019-server 使用jenkins任意版本或teamcity 
使用windows批处理命令行构建
(使用命令行直接运行无报错，使用mac平台shell在jenkins调用也无报错）

### JavaScript output or error produced?（报错信息和调用栈）
```
[1380] Start init build-worker

[1380] Error: Build Failed: Error: TypeError: Cannot read property 'getParameter' of null
    at Device._initCaps (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:591:39)
    at new Device (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:539:10)
    at Object.initWebGL (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\renderer\index.js:151:21)
    at Object._initRenderer (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:799:16)
    at Object._initEngine (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:390:10)
    at Object._prepareFinished (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:409:10)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:501:14
    at Object._loadPreviewScript (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:402:7)
    at Object.prepare (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:500:10)
    at Object.run (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:516:10)
    at IpcMainImpl.o (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:9622)
    at Object.onceWrapper (events.js:422:26)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at IpcMainImpl.<anonymous> (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor-framework\lib\main\ipc.ccc:1:3399)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)
    at Object.emit (domain.js:483:12)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\lib\builder\index.ccc:1:3950
    at wrapper (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:272:20)
    at next (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:4584:24)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:325:20
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:5879
    at Gulp.<anonymous> (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:26733)
    at Object.onceWrapper (events.js:422:26)
    at Gulp.emit (events.js:315:20)
    at Gulp.emit (domain.js:483:12)

[1380] Error: Error: TypeError: Cannot read property 'getParameter' of null
    at Device._initCaps (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:591:39)
    at new Device (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:539:10)
    at Object.initWebGL (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\renderer\index.js:151:21)
    at Object._initRenderer (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:799:16)
    at Object._initEngine (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:390:10)
    at Object._prepareFinished (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:409:10)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:501:14
    at Object._loadPreviewScript (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:402:7)
    at Object.prepare (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:500:10)
    at Object.run (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:516:10)
    at IpcMainImpl.o (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:9622)
    at Object.onceWrapper (events.js:422:26)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at IpcMainImpl.<anonymous> (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor-framework\lib\main\ipc.ccc:1:3399)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)
    at Object.emit (domain.js:483:12)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\index.ccc:1:4859
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\lib\builder\index.ccc:1:5244
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:2959:19
    at wrapper (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:272:20)
    at iterateeCallback (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:417:21)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:325:20
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:2957:17
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\lib\builder\index.ccc:1:4291
    at wrapper (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async\dist\async.js:272:20)
Uncaught Exception: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 5,
  name: 'build-common',
  branch: false,
  error: Error: TypeError: Cannot read property 'getParameter' of null
      at Device._initCaps (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:591:39)
      at new Device (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:539:10)
      at Object.initWebGL (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\renderer\index.js:151:21)
      at Object._initRenderer (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:799:16)
      at Object._initEngine (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:390:10)
      at Object._prepareFinished (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:409:10)
      at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:501:14
      at Object._loadPreviewScript (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:402:7)
      at Object.prepare (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:500:10)
      at Object.run (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:516:10)
      at IpcMainImpl.o (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:9622)
      at Object.onceWrapper (events.js:422:26)
      at IpcMainImpl.emit (events.js:315:20)
      at IpcMainImpl.emit (domain.js:483:12)
      at IpcMainImpl.<anonymous> (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor-framework\lib\main\ipc.ccc:1:3399)
      at IpcMainImpl.emit (events.js:315:20)
      at IpcMainImpl.emit (domain.js:483:12)
      at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
      at Object.emit (events.js:315:20)
      at Object.emit (domain.js:483:12),
  duration: [ 49, 155385900 ],
  time: 1620341319187
})
    at Gulp.emit (events.js:304:17)
    at Gulp.emit (domain.js:483:12)
    at Object.error (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\once\once.js:25:25)
    at f (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\once\once.js:25:25)
    at tryCatch (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async-done\index.js:24:15)
    at done (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\async-done\index.js:40:12)
    at f (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\once\once.js:25:25)
    at handler (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\node_modules\now-and-later\lib\mapSeries.js:48:16)
Error: TypeError: Cannot read property 'getParameter' of null
    at Device._initCaps (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:591:39)
    at new Device (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\renderer\gfx\device.js:539:10)
    at Object.initWebGL (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\renderer\index.js:151:21)
    at Object._initRenderer (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:799:16)
    at Object._initEngine (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:390:10)
    at Object._prepareFinished (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:409:10)
    at C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:501:14
    at Object._loadPreviewScript (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:402:7)
    at Object.prepare (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:500:10)
    at Object.run (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\engine\bin\.cache\dev\cocos2d\core\CCGame.js:516:10)
    at IpcMainImpl.o (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor\core\gulp-build.ccc:1:9622)
    at Object.onceWrapper (events.js:422:26)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at IpcMainImpl.<anonymous> (C:\CocosDashboard_1.0.12\resources\.editors\Creator\2.4.5\resources\app.asar\editor-framework\lib\main\ipc.ccc:1:3399)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.emit (domain.js:483:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)
    at Object.emit (domain.js:483:12)
```

**Comment by xianyinchen** [comment]
你好，这个报错意味着WebGL没有初始化成功，确保运行系统带有显卡，且支持GL硬件渲染。

**Comment by qx** [comment]
跟creator无关，windows登录机制问题，java －jar方式运行解决

**Comment by ppjjzz** [comment]
> 

如果用的是gitlab-runner遇到这个问题要怎么解决呢

**Comment by qx** [comment]
只能在底层启动的时候做文章

**Comment by tanghuipang** [comment]
如果是teamcity，不要用服务的方式启动agent，用命令行启动
