### ISSUE TITLE
Issue when attempting to write an extension for the inspector

### ISSUE THREAD

**Issue by laurieattwobulls** [cocos/cocos-engine#9332]
Hi,

I am trying to write an editor inspector for a component.
I have followed the [documentation](https://docs.cocos.com/creator/manual/en/extension/extends-inspector.html), but there are missing information, such as how to import Vue in the script. 
Please note that I tried to find an [example](https://github.com/chichinohaha/engine/blob/366fde679ced3ba24c74dfccf9f5c12b786401e3/editor/inspector/components/widget.js) to make the inspector extension but I could only find examples for cocos creator version 3+, so I am not sure I am using the right import for Vue. If I don't use this Vue import, the console says that Vue does not exist.

Now, I tried to make the inspector extension work, so I created a Demo project with an empty inspector view, on a very simple component that just has 1 label property. But the inspector extension doesn't load and I get an error on the console.

Please let me know how to fix this,

Cheers,

### Creator version?（版本号）
2.4.5

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
- Open the scene of the project ( there is just the one)
- Select "New Node"
- Observe the message in the console.

Cocos creator hangs from here, but you can access the log by opening the developer tools on the cocos creator menu

#### Error1
```
Failed to load script: packages://inspectors/temp-inspector.js
(anonymous) | @ | /Applications/CocosC…derer/console.ccc:1
-- | -- | --
  | (anonymous) | @ | /Applications/CocosC…/resource-mgr.ccc:1
  | n | @ | /Applications/CocosC…nderer/editor.ccc:1
  | (anonymous) | @ | /Applications/CocosC…nderer/editor.ccc:1
  | compiled | @ | /Applications/CocosC…/comp-section.ccc:1
  | (anonymous) | @ | vue.js:8396
  | (anonymous) | @ | vue.js:8789


```
#### Error 2
```
Show 22 more frames
​ Failed to load inspector node: TypeError: Cannot read property 'then' of undefined
    at CcCompSection.compiled (/Applications/CocosCreator/Creator/2.4.5/CocosCreator.app/Contents/Resources/app.asar/editor/builtin/inspector/share/comp-section.ccc:1:2584)
    at CcCompSection._callHook (app://node_modules/vue/dist/vue.js:8396:21)
    at CcCompSection._compile (app://node_modules/vue/dist/vue.js:8789:10)
    at CcCompSection.$mount (app://node_modules/vue/dist/vue.js:9607:10)
    at CcCompSection._init (app://node_modules/vue/dist/vue.js:2587:12)
    at new CcCompSection (eval at createClass (app://node_modules/vue/dist/vue.js:10148:12), <anonymous>:3:48)
    at Directive.build (app://node_modules/vue/dist/vue.js:5967:19)
    at Directive.mountComponent (app://node_modules/vue/dist/vue.js:5884:29)
    at app://node_modules/vue/dist/vue.js:5846:14
    at app://node_modules/vue/dist/vue.js:5864:7
    at /Applications/CocosCreator/Creator/2.4.5/CocosCreator.app/Contents/Resources/app.asar/editor/builtin/inspector/panel/index.ccc:1:6970
    at /Applications/CocosCreator/Creator/2.4.5/CocosCreator.app/Contents/Resources/app.asar/editor/builtin/inspector/panel/index.ccc:1:8169
```
### Demo project?（demo 项目）

https://github.com/laurieattwobulls/demo-Inspector-extension

**Comment by laurieattwobulls** [comment]
I missed the fact that the main and inspector file where not the same file.
The main.js needs to have module.exports ={} in it even if it is empty.
